import * as THREE from './assets/lib/three.module.js';

const C=window.UBCampaign;
const PALETTES=[{top:0x507d70,side:0x284a4b,edge:0xa2cab0,glow:0x7ef6bc,name:'Versunkene Gärten',english:'DROWNED GARDENS'}, {top:0x765e4f,side:0x443e3b,edge:0xd9aa72,glow:0xffb86d,name:'Eiserner Friedhof',english:'IRON GRAVEYARD'}, {top:0x46476c,side:0x292c46,edge:0xb0a5d4,glow:0xba9aff,name:'Schwarzer Graben',english:'BLACK TRENCH'}];
const $=id=>document.getElementById(id), TAU=Math.PI*2;
const hash=n=>{const x=Math.sin(n*127.1+311.7)*43758.5453;return x-Math.floor(x);};
const pt=n=>new THREE.Vector3(Math.sqrt(3)*4.2*(n.q+n.r*.5),0,6.3*n.r);
const berth=n=>pt(n).add(new THREE.Vector3(-1.4,0,1.7));
const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));

/** A persistent, reusable miniature sea chart. GLB meshes are borrowed from OceanView. */
export class Atlas {
 constructor({view,onLaunch,onHarbor,onShipyard,onSelectSound,onChange,onDock}){
  Object.assign(this,{view,onLaunch,onHarbor,onShipyard,onSelectSound,onChange,onDock});
  this.active=false;this.clock=0;this.region=0;this.zoom=1;this.pan={x:0,y:0};this.drag=null;this.ignoreClick=false;this.selected='harbor';this.nodes=new Map();this.routes=[];this.moving=false;this.route=[];this.shipHull='';
  this.scene=new THREE.Scene();this.scene.background=new THREE.Color(0x102b38);this.scene.environment=view.environment;this.scene.fog=new THREE.FogExp2(0x102b38,.002);
  this.camera=new THREE.OrthographicCamera(-40,40,25,-25,.1,260);
  this.scene.add(new THREE.HemisphereLight(0xc6ead9,0x102438,2.2));
  const sun=new THREE.DirectionalLight(0xffdfac,3.8);sun.position.set(-24,65,30);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-65,right:65,top:65,bottom:-65,near:1,far:160});sun.shadow.bias=-.0008;sun.shadow.normalBias=.08;this.scene.add(sun);this.scene.add(sun.target);sun.target.position.set(15,0,3);
  const fill=new THREE.DirectionalLight(0x74b6de,1.8);fill.position.set(30,20,-35);this.scene.add(fill);
  this.root=new THREE.Group();this.scene.add(this.root);this.buildBoard();this.mount();
  addEventListener('resize',()=>{if(this.active){if(innerWidth<720&&this.region<0)this.region=C.BY_ID[this.selected]?.stage||0;this.layout();}});
  addEventListener('keydown',e=>this.key(e));
  this.raycaster=new THREE.Raycaster();this.pointer=new THREE.Vector2();
  view.canvas.addEventListener('click',e=>{if(!this.inputReady())return;if(this.ignoreClick){this.ignoreClick=false;return;}const id=this.tileAt(e.clientX,e.clientY);if(id)this.select(id);});
  view.canvas.addEventListener('pointerdown',e=>{if(!this.inputReady()||e.button!==0)return;this.ignoreClick=false;this.drag={id:e.pointerId,x:e.clientX,y:e.clientY,startX:e.clientX,startY:e.clientY,moved:false};view.canvas.setPointerCapture(e.pointerId);});
  view.canvas.addEventListener('pointermove',e=>{if(!this.inputReady())return;const d=this.drag;if(d&&d.id===e.pointerId){const dx=e.clientX-d.x,dy=e.clientY-d.y;if(Math.hypot(e.clientX-d.startX,e.clientY-d.startY)>5)d.moved=true;if(d.moved){this.pan.x-=dx*(this.camera.right-this.camera.left)/innerWidth;this.pan.y+=dy*(this.camera.top-this.camera.bottom)/innerHeight;this.layout();this.el.classList.add('is-panning');}d.x=e.clientX;d.y=e.clientY;}else if(e.pointerType!=='touch'){const id=this.tileAt(e.clientX,e.clientY);for(const n of this.nodes.values())n.button.classList.toggle('is-hovered',n.def.id===id);}});
  const endDrag=e=>{if(this.drag?.id===e.pointerId){this.ignoreClick=this.drag.moved;this.drag=null;this.el.classList.remove('is-panning');}};
  for(const type of ['pointerup','pointercancel'])view.canvas.addEventListener(type,endDrag);
  view.canvas.addEventListener('pointerleave',()=>{for(const n of this.nodes.values())n.button.classList.remove('is-hovered');});
  const wheel=e=>{if(!this.inputReady()||e.target.closest?.('#atlas-detail,.atlas-regions,.atlas-camera,.atlas-bottom'))return;e.preventDefault();const dy=e.deltaY*(e.deltaMode===1?16:e.deltaMode===2?innerHeight:1);this.zoomBy(Math.exp(-dy*.0015));};
  view.canvas.addEventListener('wheel',wheel,{passive:false});this.el.addEventListener('wheel',wheel,{passive:false});
  addEventListener('blur',()=>{this.drag=null;this.el.classList.remove('is-panning');});
 }
 mesh(geo,material,parent=this.root){const o=new THREE.Mesh(geo,material);parent.add(o);o.receiveShadow=true;return o;}
 material(color,extra={}){return new THREE.MeshStandardMaterial({color,roughness:.7,metalness:.18,...extra});}
 miniature(name,parent,span,x=0,z=0,rotation=0){const o=this.view.clone(name,true);const box=new THREE.Box3().setFromObject(o),size=box.getSize(new THREE.Vector3()),center=box.getCenter(new THREE.Vector3());const s=span/Math.max(size.x,size.y*.83,size.z,.01);o.scale.setScalar(s);o.position.set(x-center.x*s,.13-box.min.y*s,z-center.z*s);o.rotation.y=rotation;parent.add(o);return o;}
 buildBoard(){
  const floor=this.mesh(new THREE.PlaneGeometry(500,500).rotateX(-Math.PI/2),this.material(0x153746,{roughness:.38,metalness:.48}));floor.position.y=-3.8;
  const grid=new THREE.GridHelper(300,100,0x346070,0x254653);grid.position.y=-3.77;grid.material.transparent=true;grid.material.opacity=.3;this.root.add(grid);
  const rimGeo=new THREE.TorusGeometry(4.04,.028,4,6);rimGeo.rotateX(Math.PI/2);rimGeo.rotateY(Math.PI/6);
  for(const [i,n]of C.NODES.entries()){
   const p=PALETTES[n.stage||0],g=new THREE.Group();g.position.copy(pt(n));this.root.add(g);
   const top=this.mesh(new THREE.CylinderGeometry(4.05,4.05,.4,6),this.material(p.top),g);top.position.y=-.1;top.userData.node=n.id;
   const base=this.mesh(new THREE.CylinderGeometry(4.05,3.8,2.6,6),this.material(p.side),g);base.position.y=-1.55;base.castShadow=true;
   const rim=this.mesh(rimGeo,this.material(p.edge,{metalness:.65,roughness:.3}),g);rim.position.y=.13;
   for(let band=0;band<2;band++){const line=this.mesh(new THREE.CylinderGeometry(4.065-band*.12,4.065-band*.12,.055,6),this.material(p.edge,{transparent:true,opacity:.16}),g);line.position.y=-.65-band*1.25;}
   const model=new THREE.Group();g.add(model);this.miniature(({"glockenhafen":"world-hansehaus","hansekrone":"world-hansehaus","kaiserwerk":"world-druckwerk","schmelzkessel":"world-druckwerk","nachtwarte":"world-kaiserdom","tiefenkrone":"world-kaiserdom","kaisergrab":"world-kaiserdom"})[n.id]||n.model||'shipyard',model,n.kind==='harbor'?4.6:4.3,0,-.65,-.4+(i%3)*.65);
   for(let j=0;j<4;j++){const a=j*2.399+i*.5,r=2.6+hash(i*19+j)*.6;const deco=n.stage===2?(j%2?'world-crystal':'rock-b'):n.stage===1?(j%2?'wreck':'rock-a'):(j%2?'kelp':'coral');this.miniature(deco,model,.6+hash(i*13+j)*1.05,Math.cos(a)*r,Math.sin(a)*r,a);}
   const halo=this.mesh(new THREE.RingGeometry(3.58,3.78,6).rotateX(-Math.PI/2),new THREE.MeshBasicMaterial({color:0xffd286,transparent:true,opacity:0,side:THREE.DoubleSide,depthWrite:false}),g);halo.position.y=.19;
   const beacon=this.mesh(new THREE.CylinderGeometry(.06,.06,2,6),new THREE.MeshBasicMaterial({color:p.glow}),g);beacon.position.set(2.7,1,1.2);
   const glow=new THREE.Sprite(new THREE.SpriteMaterial({map:this.view.lightTexture,color:p.glow,transparent:true,opacity:.75,blending:THREE.AdditiveBlending,depthWrite:false}));glow.position.set(2.7,2,1.2);glow.scale.setScalar(1.3);g.add(glow);
   const operations=[];if(n.kind==='mission')for(let k=0;k<4;k++){const mark=this.mesh(new THREE.CylinderGeometry(.13,.13,.19,6),new THREE.MeshStandardMaterial({color:0x83e6b9,emissive:0x285c40,roughness:.4,metalness:.5}),g);mark.position.set(-1.05+k*.7,.25,2.65);mark.visible=false;operations.push(mark);}
   this.nodes.set(n.id,{def:n,group:g,top,base,rim,halo,beacon,glow,model,operations});
  }
  const done=new Set();for(const n of C.NODES)for(const id of n.links||[]){const key=[n.id,id].sort().join(':');if(done.has(key)||!C.BY_ID[id])continue;done.add(key);const a=pt(n),b=pt(C.BY_ID[id]);a.y=.34;b.y=.34;const curve=new THREE.LineCurve3(a,b),tube=this.mesh(new THREE.TubeGeometry(curve,1,.045,5,false),new THREE.MeshBasicMaterial({color:0x92bcb1,transparent:true,opacity:.25}));tube.renderOrder=2;this.routes.push({a:n.id,b:id,tube});}
  this.shipRoot=new THREE.Group();this.root.add(this.shipRoot);
  const ring=this.mesh(new THREE.RingGeometry(1.55,1.62,64).rotateX(-Math.PI/2),new THREE.MeshBasicMaterial({color:0xffdf98,transparent:true,opacity:.75,side:THREE.DoubleSide,depthWrite:false}),this.shipRoot);ring.position.y=.17;
  const geometry=new THREE.BufferGeometry(),vertices=new Float32Array(150*3);for(let i=0;i<150;i++){vertices[i*3]=(hash(i*3)-.2)*100;vertices[i*3+1]=hash(i*9)*22;vertices[i*3+2]=(hash(i*5)-.5)*75;}geometry.setAttribute('position',new THREE.BufferAttribute(vertices,3));this.motes=new THREE.Points(geometry,new THREE.PointsMaterial({map:this.view.lightTexture,color:0xbfe9e2,size:.14,transparent:true,opacity:.42,depthWrite:false,blending:THREE.AdditiveBlending}));this.root.add(this.motes);
 }
 mount(){
  this.el=document.createElement('section');this.el.id='atlas';this.el.className='hidden';this.el.setAttribute('aria-label','Sea chart and mission selection');
  this.el.innerHTML=`<div class="atlas-heading"><span class="eyebrow">DIE SEEKARTE / EXPEDITION ATLAS</span><h1>A kingdom. <br><em>One sea at a time.</em></h1><p>Move your citadel along the chart. Conquer a tile. Open the deep.</p></div><nav class="atlas-regions" aria-label="Sea chart regions"><button data-region="-1">THE WHOLE SEA</button>${PALETTES.map((p,i)=>`<button data-region="${i}"><small>0${i+1}</small>${p.english}<span data-region-progress="${i}"></span></button>`).join('')}</nav><div id="atlas-nodes" aria-label="Mission tiles"></div><div class="atlas-camera" role="group" aria-label="Sea chart camera"><button id="atlas-zoom-out" aria-label="Zoom out">−</button><span id="atlas-zoom-level" aria-live="polite">100%</span><button id="atlas-zoom-in" aria-label="Zoom in">+</button><button id="atlas-reset" aria-label="Fit region in view">FIT</button></div><aside id="atlas-detail" aria-label="Selected mission"><div class="atlas-detail-top"><span id="atlas-sector"></span><span id="atlas-status"></span></div><div class="atlas-portrait"><img id="atlas-portrait" alt=""><span id="atlas-danger"></span></div><h2 id="atlas-title"></h2><span id="atlas-english"></span><p id="atlas-desc"></p><div id="atlas-metrics"></div><div class="atlas-order"><small>YOUR ORDERS</small><p id="atlas-objective"></p></div><p id="atlas-condition"></p><p id="atlas-lock"></p><button id="atlas-launch" class="primary"></button><small id="atlas-loadout"></small></aside><div class="atlas-bottom"><div class="atlas-home"><button id="atlas-harbor" class="secondary">← HARBOR & LOADOUT</button><button id="atlas-dock" class="secondary">SHOP & REFIT</button><button id="atlas-shipyard" class="secondary">⚒ SHIPYARD <span id="atlas-silver"></span></button></div><div class="atlas-legend"><span><i class="complete"></i> SECURED</span><span><i class="open"></i> OPEN WATER</span><span><i></i> UNCHARTED</span></div><div id="atlas-travel" role="status" aria-live="polite"></div><small class="atlas-controls">DRAG TO PAN · SCROLL TO ZOOM · CLICK A TILE TO SAIL · ENTER TO DIVE</small></div>`;
  document.body.append(this.el);
  for(const n of C.NODES){const b=document.createElement('button');b.dataset.node=n.id;b.className='atlas-node';b.setAttribute('aria-label',n.name);b.innerHTML=`<span class="atlas-node-symbol"></span><strong>${escape(n.name)}</strong><small></small>`;b.onclick=()=>this.select(n.id);$('atlas-nodes').append(b);this.nodes.get(n.id).button=b;}
  this.el.querySelectorAll('[data-region]').forEach(b=>b.onclick=()=>{this.setRegion(Number(b.dataset.region));});
  $('atlas-zoom-in').onclick=()=>this.zoomBy(1.2);$('atlas-zoom-out').onclick=()=>this.zoomBy(1/1.2);$('atlas-reset').onclick=()=>this.resetCamera();
  $('atlas-harbor').onclick=()=>this.onHarbor();$('atlas-shipyard').onclick=()=>this.onShipyard();$('atlas-dock').onclick=()=>this.onDock?.();$('atlas-launch').onclick=()=>this.launch();
 }
 show(campaign,selected,meta){this.active=true;this.el.classList.remove('hidden');this.campaign=campaign;this.loadout=selected;this.meta=meta;this.moving=false;this.route=[];this.selected=C.BY_ID[campaign.position]?campaign.position:'harbor';this.region=C.BY_ID[this.selected].stage||0;this.zoom=1;this.pan={x:0,y:0};this.drag=null;this.ignoreClick=false;this.setShip(selected.hull);this.shipRoot.position.copy(berth(C.BY_ID[this.selected]));this.refresh(campaign,selected,meta);this.layout();}
 hide(){this.active=false;this.drag=null;this.el.classList.add('hidden');this.el.classList.remove('is-panning');}
 inputReady(){return this.active&&$('modal').classList.contains('hidden');}
 tileAt(x,y){if(this.mapRect&&(x<this.mapRect.left||x>this.mapRect.right||y<this.mapRect.top||y>this.mapRect.bottom))return null;this.pointer.set(x/innerWidth*2-1,1-y/innerHeight*2);this.raycaster.setFromCamera(this.pointer,this.camera);const hit=this.raycaster.intersectObjects([...this.nodes.values()].filter(n=>n.group.visible).map(n=>n.top),false)[0];return hit?.object.userData.node||null;}
 setRegion(region){this.region=region;this.zoom=1;this.pan={x:0,y:0};this.layout();}
 resetCamera(){this.zoom=1;this.pan={x:0,y:0};this.layout();}
 zoomBy(factor){if(!this.inputReady())return;this.zoom=Math.max(.8,Math.min(3,this.zoom*factor));this.layout();}
 setShip(hull){const look=this.loadout?.appearance,signature=hull+'|'+(look?.paint?.id||'original')+'|'+(look?.emblem?.id||'none');if(signature===this.shipHull)return;if(this.ship){this.ship.removeFromParent();this.view.release(this.ship);}this.shipHull=signature;this.ship=this.view.createShip(hull,['torpedo','arc'],1,true,look);this.ship.scale.setScalar(.29);this.ship.position.set(0,1,0);this.shipRoot.add(this.ship);}
 refresh(campaign=this.campaign,selected=this.loadout,meta=this.meta){this.campaign=campaign;this.loadout=selected;this.meta=meta;if(!campaign)return;this.setShip(selected.hull);$('atlas-silver').textContent=meta.silver+' GOLD';
  for(const n of this.nodes.values()){const d=n.def,cleared=!!campaign.cleared[d.id],available=C.isUnlocked(campaign,d.id),picked=d.id===this.selected;n.available=available;n.cleared=cleared;for(const [index,mark]of n.operations.entries())mark.visible=(campaign.cleared[d.id]?.siteKinds||[]).includes(['bastion','salvage','beacon','shrine'][index]);n.button.classList.toggle('is-locked',!available);n.button.classList.toggle('is-cleared',cleared||d.kind==='harbor');n.button.classList.toggle('is-selected',picked);n.button.setAttribute('aria-pressed',String(picked));n.button.querySelector('.atlas-node-symbol').textContent=d.kind==='harbor'?'⚓':cleared?'✓':available?'◆':'⌑';n.button.querySelector('small').textContent=d.kind==='harbor'?'HOME PORT':cleared?'SECURED':available?'DIVE AVAILABLE':'LOCKED';n.button.setAttribute('aria-label',d.name+' · '+(cleared?'secured':available?'available':'locked'));n.top.material.color.setHex(PALETTES[d.stage||0].top).multiplyScalar(available?1:.56);n.model.traverse(o=>{if(o.isMesh)o.castShadow=available;});n.glow.visible=available;n.beacon.visible=available;n.halo.material.opacity=picked?.85:0;}
  for(const r of this.routes){const a=this.nodes.get(r.a),b=this.nodes.get(r.b),open=a.available&&b.available;r.tube.material.color.setHex(open?0xf2c781:0x62828a);r.tube.material.opacity=open?.65:.18;}
  for(let i=0;i<3;i++){const all=C.NODES.filter(n=>n.kind!=='harbor'&&n.stage===i);this.el.querySelector(`[data-region-progress="${i}"]`).textContent=all.filter(n=>campaign.cleared[n.id]).length+'/'+all.length;}
  this.detail();
 }
 detail(){const n=C.BY_ID[this.selected],harbor=n.kind==='harbor',cleared=!!this.campaign.cleared[n.id],available=C.isUnlocked(this.campaign,n.id);$('atlas-sector').textContent=harbor?'WERFT 07 / HOME PORT':'SEA 0'+(n.stage+1)+' / '+PALETTES[n.stage].english;$('atlas-status').textContent=harbor?'SAFE HARBOR':cleared?'SECURED':available?'ROUTE OPEN':'UNCHARTED';$('atlas-title').textContent=n.name;$('atlas-english').textContent=n.english||'';$('atlas-desc').textContent=n.desc||'Your shipyard at the edge of a drowned kingdom. Choose the first tile to begin your expedition.';$('atlas-portrait').src=this.view.thumbnail(n.model||'shipyard');$('atlas-danger').textContent=harbor?'HOME PORT':Array.from({length:5},(_,i)=>i<(n.difficulty||1)?'◆':'◇').join(' ');$('atlas-metrics').innerHTML=harbor?'<span><b>'+C.NODES.filter(n=>n.kind==='mission').length+'</b><small>SEA MISSIONS</small></span><span><b>3</b><small>REGIONS</small></span><span><b>'+Object.keys(this.campaign.cleared).length+'</b><small>SECURED</small></span>':`<span><b>${(n.bossWaves||[]).map(w=>Math.floor(w.at/60)+':'+String(w.at%60).padStart(2,'0')).join(' / ')}</b><small>3 BOSSES / MISSION TIME</small></span><span><b>${cleared?'CLAIMED':'+'+(n.reward||0)}</b><small>FIRST CLEAR GOLD</small></span>`;if(!harbor)$('atlas-metrics').querySelector('b').classList.add('atlas-boss-schedule');$('atlas-objective').textContent=harbor?'Sail to an open tile. Salvage gold, recover artifacts, and defeat all three guardians in one run to secure the area.':n.objective||'Defeat all three guardians in one run.';$('atlas-condition').textContent=harbor?'Every dive begins with your chosen hull and starting module. Banked gold, purchased loadouts, and shipyard research stay with you.':(n.enemyProfile?n.enemyProfile+' · ':'')+(n.condition||'')+' · 8 optional operations: bastions, salvage, beacons, shrines.'+(cleared?' Best secured: '+(this.campaign.cleared[n.id].bestSites||0)+'/8.':'');
  const req=(n.requires||[]).map(id=>C.BY_ID[id]?.name||id);$('atlas-lock').textContent=available?'':('Secure '+req.join(' or ')+' to open this route.');$('atlas-lock').hidden=available;
  const b=$('atlas-launch');b.disabled=this.moving||(!available&&!harbor);b.textContent=this.moving?'SAILING TO '+n.name.toUpperCase()+'…':harbor?'CHART THE FIRST DIVE ↗':!available?'ROUTE LOCKED':cleared?'DIVE AGAIN ↘':'ENTER THESE WATERS ↘';$('atlas-loadout').textContent=harbor?'CHOOSE A TILE ON THE CHART':`${window.UBContent.HULLS[this.loadout.hull].name} · ${window.UBContent.PRESSURES[this.loadout.pressure].name} · fresh mission loadout`;
 }
 select(id){if(this.moving||!C.BY_ID[id])return;const old=this.campaign.position;this.selected=id;this.onSelectSound?.();if(this.region>=0&&C.BY_ID[id].stage!==this.region){this.region=C.BY_ID[id].stage||0;this.zoom=1;this.pan={x:0,y:0};}const path=C.pathTo(this.campaign,id);if(C.isUnlocked(this.campaign,id)&&path&&path.length&&id!==old){this.route=path.map(p=>typeof p==='string'?p:p.id).filter(p=>p!==old);this.moving=this.route.length>0;this.travelTarget=id;this.travelProgress=0;this.travelFrom=this.shipRoot.position.clone();if(matchMedia('(prefers-reduced-motion: reduce)').matches){this.shipRoot.position.copy(berth(C.BY_ID[id]));this.arrive();}}this.refresh();this.layout();if(!this.moving)$('atlas-travel').textContent=C.isUnlocked(this.campaign,id)?(id===old?'CITADEL ANCHORED / '+C.BY_ID[id].name:'ROUTE SELECTED'):'UNCHARTED WATERS / SECURE THE CONNECTING AREA';}
 arrive(){const id=this.travelTarget;if(id)C.moveTo(this.campaign,id);this.moving=false;this.route=[];this.travelTarget=null;this.onChange?.(this.campaign);this.refresh();$('atlas-travel').textContent='CITADEL ANCHORED / '+C.BY_ID[this.campaign.position].name;this.onSelectSound?.();}
 launch(){if(this.moving)return;const n=C.BY_ID[this.selected];if(n.kind==='harbor'){const first=C.NODES.find(v=>v.kind!=='harbor'&&C.isUnlocked(this.campaign,v.id));if(first)this.select(first.id);return;}if(C.isUnlocked(this.campaign,n.id)&&this.campaign.position===n.id)this.onLaunch(n.id);}
 layout(){if(!this.active)return;const regions=this.el.querySelector('.atlas-regions');regions.style.top=Math.ceil(this.el.querySelector('.atlas-heading').getBoundingClientRect().bottom+14)+'px';const mobile=innerWidth<720,w=innerWidth,h=innerHeight;this.el.style.setProperty('--atlas-camera-top',(regions.getBoundingClientRect().bottom+8)+'px');if(mobile&&this.region<0)this.region=C.BY_ID[this.selected].stage||0;this.el.querySelectorAll('[data-region]').forEach(b=>b.classList.toggle('active',Number(b.dataset.region)===this.region));
  const visible=[...this.nodes.values()].filter(n=>this.region<0||n.def.stage===this.region||(n.def.kind==='harbor'&&this.region===0));for(const n of this.nodes.values()){n.group.visible=visible.includes(n);n.button.hidden=!n.group.visible;}for(const r of this.routes)r.tube.visible=this.nodes.get(r.a).group.visible&&this.nodes.get(r.b).group.visible;this.shipRoot.visible=this.nodes.get(this.campaign.position)?.group.visible||this.moving;
  const box=new THREE.Box3();for(const n of visible){const p=n.group.position;box.expandByPoint(p.clone().add(new THREE.Vector3(-4.5,-2.8,-4.5)));box.expandByPoint(p.clone().add(new THREE.Vector3(4.5,6,4.5)));}const center=box.getCenter(new THREE.Vector3());this.camera.position.copy(center).add(new THREE.Vector3(0,80,56));this.camera.lookAt(center);this.camera.updateMatrixWorld();
  const bb=new THREE.Box3();for(const n of visible)for(const x of [-4.25,4.25])for(const y of [-2.8,5.4])for(const z of [-4.25,4.25])bb.expandByPoint(n.group.position.clone().add(new THREE.Vector3(x,y,z)).applyMatrix4(this.camera.matrixWorldInverse));
  const left=mobile?18:35,right=mobile?w-18:w-355,top=regions.getBoundingClientRect().bottom+(mobile?64:12),bottom=mobile?h-(h<720?272:305):h-115;const aw=Math.max(100,right-left),ah=Math.max(100,bottom-top),span=Math.max((bb.max.y-bb.min.y)/ah*h,(bb.max.x-bb.min.x)/aw*h)*1.01/this.zoom,hh=span*.5,hw=hh*w/h;const cx=(bb.max.x+bb.min.x)*.5-((left+right)/w-1)*hw,cy=(bb.max.y+bb.min.y)*.5-(1-(top+bottom)/h)*hh;this.pan.x=THREE.MathUtils.clamp(this.pan.x,-(bb.max.x-bb.min.x)*.7,(bb.max.x-bb.min.x)*.7);this.pan.y=THREE.MathUtils.clamp(this.pan.y,-(bb.max.y-bb.min.y)*.7,(bb.max.y-bb.min.y)*.7);Object.assign(this.camera,{left:cx-hw+this.pan.x,right:cx+hw+this.pan.x,top:cy+hh+this.pan.y,bottom:cy-hh+this.pan.y});this.mapRect={left,right,top,bottom};this.camera.updateProjectionMatrix();this.placeLabels();$('atlas-zoom-level').textContent=Math.round(this.zoom*100)+'%';$('atlas-zoom-in').disabled=this.zoom>=2.999;$('atlas-zoom-out').disabled=this.zoom<=.801;
 }
 placeLabels(){const mobile=innerWidth<720,detail=this.el.querySelector('#atlas-detail').getBoundingClientRect(),toolbar=this.el.querySelector('.atlas-camera').getBoundingClientRect(),nav=this.el.querySelector('.atlas-regions').getBoundingClientRect(),footer=this.el.querySelector('.atlas-bottom').getBoundingClientRect();const edge={left:24,right:mobile?innerWidth-24:detail.left-24,top:(mobile?toolbar.bottom:nav.bottom)+24,bottom:(mobile?detail.top:footer.top)-24};for(const n of this.nodes.values()){if(!n.group.visible)continue;const p=n.group.position.clone().add(new THREE.Vector3(0,-1.4,3.6)).project(this.camera),x=(p.x*.5+.5)*innerWidth,y=(-p.y*.5+.5)*innerHeight;n.button.hidden=x<edge.left||x>edge.right||y<edge.top||y>edge.bottom;n.button.style.left=x+'px';n.button.style.top=y+'px';}}
 key(e){if(!this.active||!$('modal').classList.contains('hidden')||e.ctrlKey||e.altKey||e.metaKey||e.repeat)return;const directions={KeyW:[0,-1],ArrowUp:[0,-1],KeyS:[0,1],ArrowDown:[0,1],KeyA:[-1,0],ArrowLeft:[-1,0],KeyD:[1,0],ArrowRight:[1,0]};if(e.code==='Escape'){e.preventDefault();this.onHarbor();return;}if(e.code==='Enter'&&(!(e.target instanceof HTMLButtonElement)||e.target.hasAttribute('data-node'))){e.preventDefault();this.launch();return;}const dir=directions[e.code];if(!dir)return;e.preventDefault();if(this.moving)return;const from=this.nodes.get(this.selected),a=from.group.position.clone().project(this.camera);const options=[...this.nodes.values()].filter(n=>n!==from&&n.group.visible&&n.available).map(n=>{const b=n.group.position.clone().project(this.camera),dx=b.x-a.x,dy=-(b.y-a.y),along=dx*dir[0]+dy*dir[1],cross=Math.abs(dx*dir[1]-dy*dir[0]);return {n,along,score:Math.hypot(dx,dy)+cross*2};}).filter(v=>v.along>.01).sort((a,b)=>a.score-b.score);if(options[0])this.select(options[0].n.def.id);}
 update(dt){if(!this.active)return;this.clock+=dt;this.ship?.shipAssembly?.update(dt);if(this.moving&&this.route.length){const next=berth(C.BY_ID[this.route[0]]);this.travelProgress=Math.min(1,this.travelProgress+dt/ .65);const t=this.travelProgress,s=t*t*(3-2*t);this.shipRoot.position.lerpVectors(this.travelFrom,next,s);this.shipRoot.position.y=Math.sin(t*Math.PI)*.5;const delta=next.clone().sub(this.travelFrom);this.ship.rotation.y=Math.atan2(-delta.z,delta.x);$('atlas-travel').textContent='CITADEL UNDER WAY / '+C.BY_ID[this.route[0]].name;if(t>=1){this.route.shift();this.travelProgress=0;this.travelFrom=next.clone();if(!this.route.length)this.arrive();}}
  if(this.ship)this.ship.position.y=1.3+Math.sin(this.clock*2)*.15;for(const n of this.nodes.values()){n.halo.material.opacity=n.def.id===this.selected ? .62+Math.sin(this.clock*2.6)*.18 : 0;n.glow.material.opacity=.6+Math.sin(this.clock*2+n.def.q)*.2;}this.motes.position.y=Math.sin(this.clock*.12)*2;this.view.post.update(dt,{stage:this.region,mode:'atlas',reducedMotion:this.view.reducedMotion});this.view.post.render(this.scene,this.camera);
 }
 get state(){return {selected:this.selected,position:this.campaign?.position,moving:this.moving,marker:{x:this.shipRoot.position.x,z:this.shipRoot.position.z},available:C.NODES.filter(n=>this.campaign&&C.isUnlocked(this.campaign,n.id)).map(n=>n.id),cleared:Object.keys(this.campaign?.cleared||{}),region:this.region,zoom:this.zoom,pan:{...this.pan},viewSpan:this.camera.top-this.camera.bottom};}
}
