import {OceanView} from './view3d.js';
import {Soundscape} from './audio.js';
import {Atlas} from './atlas.js';
import {Harbor} from './harbor.js';
import {syncBossHud} from './boss-ui.js';
const Campaign=window.UBCampaign,H=window.UBHarbor;
const {Game,HULLS,CAPTAINS,CREWS,WEAPONS,RARITIES,ARTIFACTS,EVOLUTIONS,PRESSURES,RESEARCH,BIOMES,freshMeta,sanitizeMeta,purchaseResearch,researchCost,clamp}=window.Underburg;
const $=id=>document.getElementById(id),sound=new Soundscape();let game=null,meta=freshMeta(),selected={hull:'nautilus',captain:'greta',crew:'divers',weapon:'torpedo',pressure:'survey'},keys=new Set(),pointer=null,boostHeld=false,last=0,elapsed=0,wasState='menu',hudT=0,toastUntil=0,modalKind='',draftStamp='',settlement=0,pausedForHelp=false,view,atlas,savedRun=null,saveAt=0,campaign=Campaign.freshCampaign(),campaignBonus=0,harborState=H.freshHarbor(),harborUI=null,harborOrigin='menu',earnedAchievements=[];
try{meta=sanitizeMeta(JSON.parse(localStorage.getItem('underburg.meta.v2')));const s=JSON.parse(localStorage.getItem('underburg.loadout.v2'));if(s&&typeof s==='object')for(const [key,table]of Object.entries({hull:HULLS,captain:CAPTAINS,crew:CREWS,weapon:WEAPONS,pressure:PRESSURES}))if(table[s[key]])selected[key]=s[key];sound.enabled=localStorage.getItem('underburg.sound')!=='off';}catch{}
try{const raw=JSON.parse(localStorage.getItem('underburg.run.v3'));const restored=Game.restore(raw);if(restored&&!meta.settled.includes(restored.runId))savedRun=raw;}catch{}
try{campaign=Campaign.sanitizeCampaign(JSON.parse(localStorage.getItem('underburg.campaign.v1')));}catch{}
try{harborState=H.sanitizeHarbor(JSON.parse(localStorage.getItem('underburg.harbor.v1')));}catch{}
H.syncProgress(harborState,meta,campaign);if(!H.getLoadout(harborState).unlockedWeapons.includes(selected.weapon))selected.weapon='torpedo';
const DEFAULT_BINDINGS=['KeyQ','KeyE','KeyR','KeyF','KeyC','KeyV','KeyX'],BINDING_STORAGE='underburg.bindings.v1';
const RESERVED_BINDINGS=new Set(['KeyW','KeyA','KeyS','KeyD','KeyB','KeyM','Space','ShiftLeft','ShiftRight','Escape','ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Digit1','Digit2','Digit3','Digit4','Digit5','Digit6']);
const validBinding=code=>typeof code==='string'&&/^(Key[A-Z]|Digit[0789])$/.test(code)&&!RESERVED_BINDINGS.has(code);
let bindings=DEFAULT_BINDINGS.slice(),bindingCapture=-1,controlsExit=null;
try{const stored=JSON.parse(localStorage.getItem(BINDING_STORAGE));if(Array.isArray(stored)&&stored.length===7&&stored.every(validBinding)&&new Set(stored).size===7)bindings=stored.slice();}catch{}
const bindingLabel=code=>code.replace(/^Key|^Digit/,'');
const activeKeys=()=>bindings.slice(0,6).map(bindingLabel).join(' / ');
function saveBindings(){try{localStorage.setItem(BINDING_STORAGE,JSON.stringify(bindings));}catch{}syncBindingHints();if(game)syncModules();}
function syncBindingHints(){document.querySelectorAll('[data-active-keys]').forEach(e=>e.textContent=activeKeys());document.querySelectorAll('[data-all-key]').forEach(e=>e.textContent=bindingLabel(bindings[6]));}
function movementHint(){return 'WASD / arrows steer · Shift boosts · Space emits sonar · '+activeKeys()+' trigger slots 1–6 · '+bindingLabel(bindings[6])+' fires every ready ability · B opens upgrades.';}
function controlsStatus(text,error=false){const status=$('binding-status');if(status){status.textContent=text;status.classList.toggle('binding-error',error);}}
function cancelBinding(){if(bindingCapture<0)return;bindingCapture=-1;document.querySelectorAll('[data-binding]').forEach(b=>b.classList.remove('listening'));controlsStatus('Assignment cancelled. Select a key to change it.');}
function renderBindings(){
 $('choices').className='binding-grid';$('choices').innerHTML='';
 bindings.forEach((code,i)=>{const row=document.createElement('div');row.className='binding-row';const label=document.createElement('div');label.className='binding-label';const title=document.createElement('strong');title.textContent=i===6?'All ready abilities':'Active ability '+(i+1);const detail=document.createElement('small');detail.textContent=i===6?'Triggers every mounted system':game?.moduleOrder[i]?WEAPONS[game.moduleOrder[i]].name:'Weapon hardpoint '+(i+1);label.append(title,detail);const button=document.createElement('button');button.className='binding-key';button.dataset.binding=i;button.textContent=bindingLabel(code);button.setAttribute('aria-label','Rebind '+(i===6?'all ready abilities':'active ability '+(i+1))+', currently '+bindingLabel(code));button.onclick=()=>{bindingCapture=i;document.querySelectorAll('[data-binding]').forEach(b=>b.classList.toggle('listening',Number(b.dataset.binding)===i));controlsStatus('Press a new key for '+(i===6?'all ready abilities':'active ability '+(i+1))+'. Escape cancels.');};const alias=document.createElement('span');alias.className='binding-alias';alias.textContent=i===6?'SALVO':(i+1)+' ALSO WORKS';row.append(label,button,alias);$('choices').append(row);});
}
function showControls(origin='header'){
 const resume=game?.state==='playing',helpResume=pausedForHelp;if(resume){game.state='paused';checkpoint();}
 showModal('controls','STEERING STATION / TASTENBELEGUNG','Keep your hands <em>on the helm.</em>','Six active abilities sit beside WASD. Select any key below, then press its replacement. Changes are saved automatically.');
 controlsExit=()=>{bindingCapture=-1;if(origin==='pause'&&game){game.state='playing';pause();}else if(origin==='help'){if(helpResume&&game)game.state='playing';help();}else{closeModal();if(resume&&game)game.state='playing';}};
 $('modal-info').innerHTML='<div class="fixed-bindings"><span><kbd>WASD / ↑↓←→</kbd> STEER</span><span><kbd>SHIFT</kbd> BOOST</span><span><kbd>SPACE</kbd> SONAR</span></div><p id="binding-status" role="status" aria-live="polite">Select a key to change it. Number keys 1–6 always remain available.</p><p class="binding-note">Movement, B (upgrades), M (sound), Escape, and 1–6 are reserved. Use a letter or 0, 7, 8, 9. Each action needs its own key. Bindings use physical key positions.</p>';
 renderBindings();action('DONE',()=>controlsExit(),true);action('RESET DEFAULTS',()=>{bindingCapture=-1;bindings=DEFAULT_BINDINGS.slice();saveBindings();renderBindings();controlsStatus('Default keys restored: Q / E / R / F / C / V. X fires every ready ability.');});focusModal();
}
function captureBinding(e){
 if(bindingCapture<0)return false;
 if(e.code==='Tab'){cancelBinding();return true;}
 e.preventDefault();e.stopPropagation();if(e.repeat)return true;
 if(e.code==='Escape'){cancelBinding();return true;}
 if(e.ctrlKey||e.altKey||e.metaKey||e.shiftKey||!validBinding(e.code)){controlsStatus('That key is reserved. Choose an unused letter or 0, 7, 8, 9.',true);return true;}
 const slot=bindings.indexOf(e.code);if(slot>=0&&slot!==bindingCapture){controlsStatus(bindingLabel(e.code)+' already activates '+(slot===6?'all ready abilities':'ability '+(slot+1))+'. Choose a different key.',true);return true;}
 const i=bindingCapture;bindings[i]=e.code;bindingCapture=-1;saveBindings();renderBindings();document.querySelector('[data-binding="'+i+'"]').focus();controlsStatus((i===6?'All ready abilities':'Ability '+(i+1))+' is now bound to '+bindingLabel(e.code)+'.');return true;
}
function save(){try{localStorage.setItem('underburg.meta.v2',JSON.stringify(meta));localStorage.setItem('underburg.loadout.v2',JSON.stringify(selected));localStorage.setItem('underburg.campaign.v1',JSON.stringify(campaign));localStorage.setItem('underburg.harbor.v1',JSON.stringify(harborState));}catch{}}
function checkpoint(){if(!game)return;try{if(['lost','won'].includes(game.state)){localStorage.removeItem('underburg.run.v3');savedRun=null;}else{savedRun=game.snapshot();localStorage.setItem('underburg.run.v3',JSON.stringify(savedRun));}}catch{}saveAt=elapsed+5;}
function toast(text,time=4){$('toast').textContent=text;toastUntil=elapsed+time;$('toast').style.opacity='1';}
function flash(color='#a9efcf'){const e=$('cinematic-flash');e.style.background=color;e.animate([{opacity:.15},{opacity:0}],{duration:550,easing:'ease-out'});}
function fmt(t){return Math.floor(t/60).toString().padStart(2,'0')+':'+Math.floor(t%60).toString().padStart(2,'0');}
function showModal(kind,kicker,title,desc){modalKind=kind;keys.clear();pointer=null;boostHeld=false;const m=$('modal');m.classList.remove('hidden');m.classList.remove('universe-reward');m.classList.toggle('reward-reveal',['draft','sector','end'].includes(kind));$('modal-kicker').textContent=kicker;$('modal-title').innerHTML=title;$('modal-desc').textContent=desc;$('modal-info').innerHTML='';$('choices').className='';$('choices').innerHTML='';$('modal-actions').innerHTML='';}
function closeModal(){bindingCapture=-1;$('modal').classList.add('hidden');modalKind='';keys.clear();pointer=null;boostHeld=false;$('choices').innerHTML='';$('modal-actions').innerHTML='';if(atlas?.active)atlas.refresh(campaign,{...selected,appearance:H.getLoadout(harborState)},meta);}
function action(label,fn,primary=false,disabled=false){const b=document.createElement('button');b.textContent=label;b.className=primary?'primary':'secondary';b.disabled=disabled;b.onclick=fn;$('modal-actions').append(b);return b;}
function focusModal(){const b=$('choices').querySelector('button:not(:disabled)')||$('modal-actions').querySelector('button:not(:disabled)');b?.focus();}
function card({key,name,english,desc,icon,rarity='common',tag='',price='',disabled=false,onclick,selected=false,model=null}){const b=document.createElement('button');b.className='choice'+(selected?' selected':'');b.dataset.choice=key;b.dataset.rarity=rarity;b.style.setProperty('--rarity',RARITIES[rarity]?.color||'#a4d7bb');b.disabled=disabled;b.innerHTML='<span class="choice-icon">'+icon+'</span><span class="rarity">'+(RARITIES[rarity]?.name||rarity)+'</span><strong>'+name+'</strong>'+(english?'<span class="english">'+english+'</span>':'')+'<p>'+desc+'</p><span class="tag">'+tag+'</span>'+(price?'<span class="price">'+price+'</span>':'');if(model&&view){const url=view.thumbnail(model);if(url){const img=document.createElement('img');img.src=url;img.alt='';img.className='model-portrait';b.querySelector('.choice-icon').replaceChildren(img);b.classList.add('has-model');}}if(onclick)b.onclick=onclick;$('choices').append(b);return b;}
function applyLook(){const look=H.getLoadout(harborState);view?.setMenuHull(selected.hull,look);if(atlas?.active)atlas.refresh(campaign,{...selected,appearance:look},meta);}
function showHarbor(tab='shop'){if(!harborUI||view.loading||game&&!['won','lost'].includes(game.state))return;harborOrigin=atlas?.active?'atlas':'menu';atlas?.hide();closeModal();game=null;view.setGame(null);view.harborPreview=true;applyLook();$('menu').classList.add('hidden');$('hud').classList.add('hidden');$('pause').classList.add('hidden');wasState='harbor';harborUI.show(harborState,meta,campaign,tab);sound.start();}
function closeHarbor(){harborUI?.hide();view.harborPreview=false;save();if(harborOrigin==='atlas')openAtlas();else home();}
function updateMenu(){
 syncBindingHints();
 const achievementCount=$('achievement-count');if(achievementCount)achievementCount.textContent=harborState.achievements.length+'/'+H.ACHIEVEMENTS.length;
 $('resume-run').classList.toggle('hidden',!savedRun);$('pressure-select').querySelector('strong').textContent=PRESSURES[selected.pressure].name;
 $('hulls').innerHTML=Object.entries(HULLS).map(([key,h])=>'<button class="hull '+(key===selected.hull?'selected':'')+'" data-hull="'+key+'"><span class="icon">'+({nautilus:'◈',bastion:'▰',wraith:'⋈'})[key]+'</span><strong>'+h.name+'</strong><small>'+h.title+'</small></button>').join('');document.querySelectorAll('[data-hull]').forEach(b=>b.onclick=()=>{selected.hull=b.dataset.hull;view?.setMenuHull(selected.hull,H.getLoadout(harborState));sound.start();sound.tone(220,.18,'sine',.045,440);updateMenu();save();});$('hull-desc').textContent=HULLS[selected.hull].desc;
 $('captain-select').querySelector('strong').textContent=CAPTAINS[selected.captain].name;$('crew-select').querySelector('strong').textContent=CREWS[selected.crew].name;$('weapon-select').querySelector('strong').textContent=WEAPONS[selected.weapon].name;$('hero-name').textContent=({nautilus:'U-01',bastion:'U-02',wraith:'U-03'})[selected.hull]+' / '+HULLS[selected.hull].name.toUpperCase();$('record').textContent=meta.bestLevel?'BEST / CLASS '+Math.min(4,1+Math.floor((meta.bestLevel-1)/4))+' · '+meta.wins+' WINS':'';$('meta-silver').textContent=meta.silver+' SILVER';$('collection-count').textContent=meta.discovered.length+' / '+Object.keys(ARTIFACTS).length;$('sound').textContent=sound.enabled?'SOUND ON':'SOUND OFF';
}
function selectLoadout(kind){const table=kind==='captain'?CAPTAINS:kind==='crew'?CREWS:kind==='pressure'?PRESSURES:WEAPONS;showModal('loadout','WERFT 07 / EXPEDITION LOADOUT',kind==='captain'?'Choose your <em>captain.</em>':kind==='crew'?'Every citadel needs <em>a crew.</em>':kind==='pressure'?'How deep is <em>your ambition?</em>':'Choose your <em>first weapon.</em>','Every option is a different way to build an empire. Select one for your next expedition.');if(kind==='weapon')$('choices').className='selection-grid';for(const [key,d]of Object.entries(table)){const locked=kind==='weapon'&&!H.getLoadout(harborState).unlockedWeapons.includes(key);card({key,name:d.name,english:d.role||d.subtitle||d.english,desc:d.desc+(d.ability?' Active: '+d.ability:''),icon:d.icon||'◎',model:kind==='weapon'?'module-'+key:null,rarity:locked?'common':'rare',disabled:locked,tag:locked?'LOCKED / SEE SHOP & ACHIEVEMENTS':kind==='weapon'?d.slot+' / '+d.family.toUpperCase():kind.toUpperCase(),selected:selected[kind]===key,onclick:()=>{selected[kind]=key;save();updateMenu();closeModal();sound.start();sound.tone(440,.3,'sine',.04,659);}});}if(kind==='weapon')action('SHOP & UNLOCKS',()=>showHarbor('shop'));action('BACK TO HARBOR',closeModal);focusModal();}
function showResearch(){const fromAtlas=!!atlas?.active;showModal('research','SILVER RESERVES / '+meta.silver,'A stronger <em>shipyard.</em>','Silver is banked when an expedition ends. These improvements persist across every future descent.');$('choices').className='research-grid';for(const [key,d]of Object.entries(RESEARCH)){const rank=meta.research[key]||0,cost=researchCost(meta,key),full=rank>=d.max;card({key,name:d.name,english:'PERMANENT RESEARCH · '+rank+' / '+d.max,desc:d.desc,icon:{hull:'▰',purse:'◈',magnet:'◎',weapon:'✣',reroll:'⚒'}[key],rarity:'rare',tag:full?'FULLY RESEARCHED':'APPLIES TO FUTURE EXPEDITIONS',price:full?'COMPLETE':'<span>RESEARCH</span><b>'+cost+' SILVER</b>',disabled:full||meta.silver<cost,onclick:()=>{if(purchaseResearch(meta,key)){save();updateMenu();sound.start();sound.chord([220,330,440],.6,.05);showResearch();}}});}action(fromAtlas?'RETURN TO SEA CHART':'RETURN TO HARBOR',closeModal);focusModal();}
function showArchive(){showModal('archive','RELIC ARCHIVE / '+meta.discovered.length+' DISCOVERED','Things the ocean <em>kept.</em>','Artifacts are recovered from sealed vaults during expeditions. Discovered relics remain recorded here. Their effects apply only to the run in which they are recovered.');$('choices').className='archive-grid';for(const [key,d]of Object.entries(ARTIFACTS)){const found=meta.discovered.includes(key);const b=card({key,name:d.name,english:d.english,desc:d.desc,icon:d.icon,model:'relic-'+key,rarity:d.rarity,tag:found?'DISCOVERED / '+d.tag:'UNDISCOVERED / '+d.tag,onclick:()=>{}});if(!found)b.classList.add('locked');b.tabIndex=-1;}action('RETURN TO HARBOR',closeModal);focusModal();}
function showDraft(){if(game?.state!=='draft')return;const kind=game.draftKind;draftStamp=kind+'|'+game.choices.map(c=>c.id+c.rarity+c.cost).join('|')+'|'+game.rerollsUsed;
 const title=kind==='artifact'?'The deep gives <em>something back.</em>':kind==='module'?'Your fortress needs <em>more teeth.</em>':kind==='evolution'?'Engineering becomes <em>alchemy.</em>':'Turn gold into <em>firepower.</em>';
 showModal('draft',kind==='artifact'?'SEALED VAULT / ARTIFACT RECOVERED':kind==='module'?'CITADEL EXPANSION / NEW HARDPOINT':kind==='evolution'?'FIVE IMPROVEMENTS / WEAPON EVOLUTION':'SHIPYARD SIGNAL / WEAPON UPGRADE',title,kind==='artifact'?'Choose one recovered artifact. Effects stack and combine with your weapons.':kind==='module'?'Choose a new mounted system. It adds an automatic attack and an active ability.':kind==='evolution'?'Choose one permanent specialization for this expedition. Your weapon is about to do something extraordinary.':'Choose one improvement for a mounted weapon. Rarity changes the strength of the upgrade.');$('modal-info').textContent=game.gold+' GOLD  ·  '+game.moduleOrder.length+' MOUNTED SYSTEMS'+(game.art.nextDouble&&kind==='artifact'?'  ·  NEXT ARTIFACT HAS DOUBLE STRENGTH':'');
 for(const c of game.choices){let d,desc,english,tag;if(kind==='evolution'){const e=EVOLUTIONS[c.key].find(e=>e.id===c.evolution);d={...e,icon:WEAPONS[c.key].icon};desc=e.desc;english=WEAPONS[c.key].name;tag='PERMANENT MODULE SPECIALIZATION';}else if(kind==='artifact'){d=ARTIFACTS[c.key];desc=(c.factor>1?'Base effect: ':'')+d.desc+(c.factor>1?' '+c.factor.toFixed(2)+'× artifact strength from this quality.':'');english=d.english;tag=d.tag;}else{d=WEAPONS[c.key];english=d.subtitle;tag=d.slot+' / '+d.family.toUpperCase();if(kind==='module')desc=d.desc+' Active: '+d.ability+(c.amount>0?' Starts with +'+c.amount+' ranks in attack, ability, and reload.':'');else {const m=game.modules[c.key],s=game.weaponStats(c.key),f=c.amount;if(c.stat==='auto')desc='Automatic attack: '+Math.round(s.damage)+' → '+Math.round(s.damage*(1+(m.auto+f)*.18)/(1+m.auto*.18))+' damage.';if(c.stat==='ability')desc='Active ability power: '+Math.round(s.ability*100)+'% → '+Math.round((s.ability+f*.3)*100)+'%.';if(c.stat==='reload'){const auto=s.cooldown*Math.max(.24,1-(m.reload+f)*.075)/Math.max(.24,1-m.reload*.075),active=s.active*Math.max(.45,1-(m.reload+f)*.04)/Math.max(.45,1-m.reload*.04);desc='Automatic cycle: '+s.cooldown.toFixed(2)+'s → '+auto.toFixed(2)+'s. Active recovery: '+s.active.toFixed(1)+'s → '+active.toFixed(1)+'s.';}tag=({auto:'AUTOMATIC ATTACK',ability:'ACTIVE ABILITY',reload:'RELOAD / COOLDOWN'})[c.stat]+' / +'+f+' RANK'+(!m.evolution?' · '+(m.purchases||0)+'/5 TO EVOLVE':'');}}
  card({key:c.id,name:d.name,english,desc,icon:d.icon,model:(kind==='artifact'?'relic-':'module-')+c.key,rarity:c.rarity,tag,price:c.cost?'<span>INSTALL IMPROVEMENT</span><b>'+c.cost+' GOLD</b>':'<span>'+(kind==='artifact'?'RECOVER ARTIFACT':kind==='evolution'?'EVOLVE WEAPON':'INSTALL MODULE')+'</span><b>CLAIM</b>',disabled:game.gold<c.cost,onclick:()=>{if(game.choose(c.id)){closeModal();syncModules();syncArtifacts();syncHud();if(kind==='artifact'||kind==='evolution')flash(RARITIES[c.rarity].color);checkpoint();}}});
 }
 const ladder=document.createElement('div');ladder.className='rarity-ladder';for(const key of ['common','rare','epic','legendary','universe']){const badge=document.createElement('span');badge.style.color=RARITIES[key].color;badge.textContent=RARITIES[key].name+' ×'+RARITIES[key].factor;ladder.append(badge);}$('modal-info').append(ladder);$('modal').classList.toggle('universe-reward',game.choices.some(c=>c.rarity==='universe'));
 const free=Math.max(0,game.freeRerolls-game.rerollsUsed),rerollCost=free?0:8+(game.rerollsUsed-game.freeRerolls)*5;if(kind!=='evolution')action(free?'REROLL / '+free+' FREE':'REROLL / '+rerollCost+' GOLD',()=>{if(game.reroll())showDraft();},false,game.gold<rerollCost);if(kind==='upgrade')action('BANK GOLD & KEEP DIVING',()=>{game.bank();closeModal();},false);focusModal();
}
function syncModules(){if(!game)return;const oldFocus=document.activeElement?.dataset?.weapon;$('modules').innerHTML=game.moduleOrder.map((key,i)=>{const w=WEAPONS[key];return '<button class="weapon ready '+(game.modules[key].evolution?'evolved':'')+'" data-weapon="'+key+'" aria-label="Activate '+w.name+' ('+bindingLabel(bindings[i])+' or '+(i+1)+')" aria-keyshortcuts="'+bindingLabel(bindings[i])+' '+(i+1)+'" title="'+w.ability+' · '+bindingLabel(bindings[i])+' or '+(i+1)+'"><span class="w-key">'+bindingLabel(bindings[i])+'</span><b>'+w.icon+'</b><strong>'+w.name+'</strong><small>ACTIVE READY</small><i class="cooldown"></i></button>';}).join('');document.querySelectorAll('[data-weapon]').forEach((b,i)=>b.onclick=()=>game?.activate(i));if(oldFocus)document.querySelector('[data-weapon="'+oldFocus+'"]')?.focus();}
function syncArtifacts(){if(!game)return;$('artifact-strip').innerHTML=game.artifacts.map(a=>{const d=ARTIFACTS[a.key];return '<button class="artifact-chip" data-artifact="'+a.key+'" title="'+d.name+(a.factor>1?' ×'+a.factor:'')+' — '+d.desc+'" style="color:'+RARITIES[a.rarity||d.rarity].color+'">'+d.icon+'</button>';}).join('');document.querySelectorAll('[data-artifact]').forEach(b=>b.onclick=()=>{const d=ARTIFACTS[b.dataset.artifact];toast(d.name+' · '+d.desc,6);});}
function syncHud(){if(!game)return;const g=game,p=g.p,b=g.enemies.filter(e=>e.kind==='boss'&&e.hp>0).sort((a,b)=>Math.hypot(a.x-p.x,a.y-p.y)-Math.hypot(b.x-p.x,b.y-p.y))[0],mission=Campaign.BY_ID[g.missionId];$('objective').textContent=mission?.name||'Salvage. Grow. Rule.';const nearby=(g.world?.landmarks||[]).map(site=>({site,d:Math.hypot(site.x-p.x,site.y-p.y)})).filter(v=>v.d<v.site.radius*2).sort((a,b)=>a.d-b.d)[0];const location=$('location-chip');location.classList.toggle('hidden',!nearby);if(nearby){location.querySelector('strong').textContent=nearby.site.name;location.querySelector('small').textContent=(g.discovered?.includes(nearby.site.id)?'CHARTED / ':'APPROACHING / ')+nearby.site.english;}$('health-fill').style.width=clamp(p.hp/p.max*100,0,100)+'%';$('health-fill').style.background=p.hp/p.max<.3?'#ed9279':'#9de6c6';$('health-text').textContent=Math.ceil(p.hp)+' / '+Math.round(p.max);$('xp-fill').style.width=clamp(g.xp/g.need*100,0,100)+'%';$('xp-text').textContent=g.xp+' / '+g.need;$('level').textContent='LV '+g.level;$('tier-label').textContent=['CLASS I / EXPLORER','CLASS II / STRONGHOLD','CLASS III / CITADEL','CLASS IV / LEVIATHAN'][g.tier-1];$('gold').textContent=g.gold;$('silver').textContent=g.silver+' SILVER BANKED';$('biome').textContent='0'+(g.stage+1)+' / '+g.biome.name.toUpperCase();$('clock').textContent=fmt(g.time);$('depth').textContent=Math.floor(g.biome.depth+g.stageTime*1.7)+' m';syncBossHud(g,fmt);$('sonar-time').textContent=p.sonar>0?Math.ceil(p.sonar)+'s':'SPACE / READY';$('sonar').disabled=p.sonar>0||g.state!=='playing';$('boost-time').textContent=Math.floor(p.energy/p.maxEnergy*100)+'% / SHIFT';$('buy-upgrade').disabled=g.state!=='playing'||g.gold<g.upgradePrice();$('buy-upgrade').textContent='B / UPGRADE · '+g.upgradePrice()+' G';
 document.querySelectorAll('[data-weapon]').forEach(b=>{const m=g.modules[b.dataset.weapon],s=g.weaponStats(b.dataset.weapon);b.disabled=g.state!=='playing'||m.active>0;b.classList.toggle('ready',m.active<=0);b.querySelector('small').textContent=m.active>0?Math.ceil(m.active)+'s RECHARGING':'ACTIVE READY';b.querySelector('.cooldown').style.width=clamp((1-m.active/s.active)*100,0,100)+'%';});$('combo').classList.toggle('hidden',g.combo<5);$('combo').textContent=g.combo+' SUNK / UNBROKEN';
 let target=b;let label=b?(b.bossName||g.biome.boss):null;if(!target){let d=Infinity;for(const prop of g.props){if(prop.used||prop.kind!=='chest')continue;const q=Math.hypot(prop.x-p.x,prop.y-p.y);if(q<d){d=q;target=prop;label='SEALED VAULT';}}}const marker=$('nav-marker');if(target){let point=view.project(target.x,target.y,7),d=Math.hypot(target.x-p.x,target.y-p.y);const xx=clamp(point.x,90,innerWidth-110),yy=clamp(point.y,205,innerHeight-245);marker.style.left=xx+'px';marker.style.top=yy+'px';marker.textContent=label+' · '+Math.round(d)+'m';marker.style.color=b?'#efa28d':'#ebc989';marker.style.display=d<80?'none':'block';}else marker.style.display='none';radar();
}
function radar(){const c=$('radar'),x=c.getContext('2d'),g=game;if(!g)return;x.clearRect(0,0,150,150);x.fillStyle='#062431dd';x.beginPath();x.arc(75,75,67,0,Math.PI*2);x.fill();x.strokeStyle='#a3dcc538';for(const r of [22,44,66]){x.beginPath();x.arc(75,75,r,0,Math.PI*2);x.stroke();}x.save();x.beginPath();x.arc(75,75,66,0,Math.PI*2);x.clip();const boundary=window.UBWorld.boundaryVertices(g.stage);x.strokeStyle='#b2e3beaa';x.lineWidth=1.5;x.beginPath();boundary.forEach((p,i)=>{const px=75+(p.x-g.p.x)/18,py=75+(p.y-g.p.y)/18;if(i)x.lineTo(px,py);else x.moveTo(px,py);});x.closePath();x.stroke();x.lineWidth=1;const a=elapsed*.8;x.strokeStyle='#98e4c280';x.beginPath();x.moveTo(75,75);x.lineTo(75+Math.cos(a)*68,75+Math.sin(a)*68);x.stroke();const dot=(o,color,r)=>{const px=75+(o.x-g.p.x)/18,py=75+(o.y-g.p.y)/18;x.fillStyle=color;x.beginPath();x.arc(px,py,r,0,Math.PI*2);x.fill();};for(const p of g.props)if(!p.used&&['chest','repair','shipyard'].includes(p.kind))dot(p,p.kind==='chest'?'#eac37c':p.kind==='repair'?'#96e6bd':'#99ceea',2);for(const site of g.world?.landmarks||[])dot(site,g.discovered?.includes(site.id)?'#a5dfc4':'#778f95',3);for(const e of g.enemies)dot(e,e.kind==='shoal'?'#819f94':'#e18d75',e.kind==='boss'?5:e.kind==='elite'?3:1.6);dot(g.p,'#dcefd7',3);x.restore();}
function openAtlas(){
 if(!atlas||view.loading||view.error)return;harborUI?.hide();view.harborPreview=false;
 if(game&&!['won','lost'].includes(game.state))checkpoint();
 game=null;view.setGame(null);keys.clear();pointer=null;boostHeld=false;closeModal();
 $('menu').classList.add('hidden');$('hud').classList.add('hidden');$('pause').classList.add('hidden');wasState='atlas';
 atlas.show(campaign,{...selected,appearance:H.getLoadout(harborState)},meta);sound.start();save();
}
function start(force=false,missionId=null){
 if(view.loading||view.error)return;
 const mission=missionId===null?null:Campaign.BY_ID[missionId];
 if(missionId!==null&&(!mission||missionId==='harbor'||!Campaign.isUnlocked(campaign,missionId))){openAtlas();return;}
 if(savedRun&&!game&&force!==true){
  showModal('saved','EXPEDITION SIGNAL RECOVERED','A citadel is <em>still out there.</em>','Resume your saved expedition, or replace it with '+(mission?mission.name:'a new departure')+'.');
  action('RESUME SAVED EXPEDITION',resumeRun,true);action(mission?'BEGIN THIS MISSION':'START A NEW EXPEDITION',()=>start(true,missionId));action('BACK',closeModal);focusModal();return;
 }
 if(missionId!==null&&!Campaign.moveTo(campaign,missionId)){openAtlas();return;}save();closeModal();atlas?.hide();
 harborUI?.hide();view.harborPreview=false;game=new Game({...selected,meta,mission:missionId,harbor:harborState});view.setGame(game);wasState='playing';settlement=0;campaignBonus=0;earnedAchievements=[];keys.clear();pointer=null;boostHeld=false;
 $('menu').classList.add('hidden');$('hud').classList.remove('hidden');$('pause').classList.remove('hidden');$('ship-name').textContent=HULLS[selected.hull].name.toUpperCase();$('pause').textContent='Ⅱ PAUSE';
 sound.start();sound.chord([73.42,146.83,220],2,.065);syncModules();syncArtifacts();syncHud();checkpoint();
 toast(mission?mission.name+' / '+mission.objective:'Gold trail ahead. Consume smaller habitats and salvage wrecks. Find the sealed vault.',6);
}
function resumeRun(){if(!savedRun||view.loading)return;const restored=Game.restore(savedRun);if(!restored){savedRun=null;updateMenu();return;}atlas?.hide();game=restored;if(game.missionId){Campaign.moveTo(campaign,game.missionId);save();}if(game.state==='paused')game.state='playing';view.setGame(game);keys.clear();pointer=null;boostHeld=false;settlement=0;campaignBonus=0;earnedAchievements=[];$('menu').classList.add('hidden');$('hud').classList.remove('hidden');$('pause').classList.remove('hidden');$('pause').textContent='Ⅱ PAUSE';$('ship-name').textContent=HULLS[game.hull].name.toUpperCase();closeModal();sound.start();syncModules();syncArtifacts();syncHud();wasState='restoring';toast('SIGNAL RECOVERED / Your expedition continues.');}
function home(){harborUI?.hide();view.harborPreview=false;atlas?.hide();game=null;view.setGame(null);view.setMenuHull(selected.hull,H.getLoadout(harborState));wasState='menu';closeModal();$('menu').classList.remove('hidden');$('hud').classList.add('hidden');$('pause').classList.add('hidden');updateMenu();}
function pause(){if(!game)return;if(game.state==='paused'){game.state='playing';closeModal();$('pause').textContent='Ⅱ PAUSE';return;}if(game.state!=='playing')return;game.state='paused';checkpoint();showModal('pause','FUNKSTILLE / SIGNAL ON HOLD','A moment of <em>quiet.</em>',movementHint());$('modal-info').textContent=game.gold+' GOLD · '+game.artifacts.length+' ARTIFACTS · '+game.kills+' HOSTILES SUNK';action('RESUME EXPEDITION',pause,true);action('REVIEW BUILD',showBuild);action('KEY BINDINGS',()=>showControls('pause'));action('END EXPEDITION',()=>{showModal('abandon','RETURN TO THE SHIPYARD','Bring the salvage <em>home.</em>','End this expedition and bank earned silver. Your current gold and installed systems belong to this run.');action('KEEP DIVING',pause,true);action('END & BANK SILVER',()=>{game.state='lost';showEnd(true);});});$('pause').textContent='▶ RESUME';focusModal();}
function showBuild(){showModal('build','CURRENT CITADEL','Anatomy of <em>an empire.</em>',CAPTAINS[game.captain].name+' · '+CREWS[game.crew].name+' · '+HULLS[game.hull].name);$('choices').className='selection-grid';for(const key of game.moduleOrder){const w=WEAPONS[key],s=game.weaponStats(key),m=game.modules[key];card({key,name:w.name,english:w.subtitle,desc:Math.round(s.damage)+' automatic damage / '+s.cooldown.toFixed(2)+'s. '+w.ability,icon:w.icon,model:'module-'+key,rarity:m.rarity==='universe'?'universe':m.evolution?'legendary':m.rarity||'common',tag:(m.evolution?EVOLUTIONS[key].find(e=>e.id===m.evolution)?.name+' / ':'')+'AUTO '+m.auto+' · ACTIVE '+m.ability+' · RELOAD '+m.reload});}action('BACK',()=>{game.state='playing';pause();});action('RESUME EXPEDITION',pause,true);focusModal();}
function help(){pausedForHelp=game?.state==='playing';if(pausedForHelp)game.state='paused';showModal('help','FIELD MANUAL / DIENSTVORSCHRIFT','How to rule <em>the deep.</em>','Steer with WASD, arrows, or drag on the water. Hold Shift for overdrive. Weapons fire automatically; '+activeKeys()+' activate slots 1–6. '+bindingLabel(bindings[6])+' activates all ready weapons. Number keys 1–6 also work. Space emits sonar and cancels incoming projectiles.');$('modal-info').innerHTML='<p>Follow gold trails. Consume wrecks and smaller habitats to grow. Find vaults for a choice of three artifacts. Buy stronger attacks, abilities, and reloads with gold. Choose an open sea-chart location and sail there to launch its mission. Defeat all three guardians in one run to chart new routes. They arrive at 4:00, 7:00, and 9:00 of mission time, even if an earlier guardian is still alive. Each early victory repairs your hull and offers an artifact. Pausing or choosing a reward pauses the mission clock. Bank silver at mission end, visit the shop for fittings and blueprints, and equip your hull finish and insignia. Achievements unlock unique equipment. Common, Rare, Epic, Legendary, and Universe rewards grant progressively stronger upgrades.</p><p style="margin-top:16px">Green beacons repair your hull. Gold signals mark artifact vaults. Larger habitats require a higher citadel class. The surrounding reef cliffs mark the edge of each navigable basin. Mouse wheel changes camera distance. Escape pauses. M toggles sound.</p><p style="margin-top:16px">Watch for mine layers leaving armed depth charges, snipers drawing a red aim line, and carriers launching interceptors. Siphon leeches latch onto your hull and drain energy: use sonar or hold overdrive to shake them loose.</p>';action('UNDERSTOOD',()=>{closeModal();if(pausedForHelp&&game){game.state='playing';pausedForHelp=false;}},true);action('KEY BINDINGS',()=>showControls('help'));focusModal();}
function showSector(){showModal('sector','GUARDIAN DEFEATED / SEA REGION SECURED','The next sea <em>calls.</em>',game.biome.boss+' is broken. Recover your spoils, repair your hull, and choose whether to descend further.');$('modal-info').innerHTML='<div class="results"><div><strong>'+game.gold+'</strong><small>GOLD CARRIED</small></div><div><strong>'+game.silver+'</strong><small>SILVER BANKED</small></div><div><strong>'+game.artifacts.length+'</strong><small>ARTIFACTS RECOVERED</small></div></div><p>Next: '+BIOMES[game.stage+1].name+' — '+BIOMES[game.stage+1].desc+'</p>';action('DESCEND TO THE NEXT SEA',()=>{if(game.nextSector()){closeModal();view.setGame(game);syncModules();syncHud();toast('New waters. A recovered artifact and a new hardpoint await.',5);}},true);action('EXTRACT WITH YOUR SPOILS',()=>{game.extract();showEnd();});focusModal();}
function showEnd(abandoned=false){
 const mission=Campaign.BY_ID[game.missionId],reward=game.settlement(meta),bonus=Campaign.recordResult(campaign,game);
 const unlocked=H.recordResult(harborState,game,campaign);if(unlocked.length){earnedAchievements=unlocked;sound.event({type:'achievement'});}if(reward!==false)settlement=reward;if(bonus>0){campaignBonus=bonus;meta.silver+=bonus;}save();checkpoint();
 const won=game.state==='won';
 showModal('end',won?(mission?'MISSION COMPLETE / SEA CHART UPDATED':'EXPEDITION COMPLETE / THE DEEP REMEMBERS'):abandoned?'EXPEDITION RECALLED / SILVER SECURED':'TRANSMISSION LOST / SALVAGE SECURED',won?(mission?'Waters <em>secured.</em>':'An empire <em>below the tide.</em>'):abandoned?'Live to build <em>another day.</em>':'Steel sinks. <em>Ambition survives.</em>',won?(mission?mission.name+' is secured. All three guardians are defeated. Return to the sea chart to choose your next destination.':'Your citadel returns with the wealth and secrets of a drowned world. The next expedition begins at the shipyard.'):'The voyage ends, but its silver and discoveries come home. Invest in your shipyard and try a different combination.');
 $('modal-info').innerHTML='<div class="results"><div><strong>'+(settlement+campaignBonus)+'</strong><small>SILVER EARNED</small></div><div><strong>'+game.goldEarned+'</strong><small>GOLD RECOVERED</small></div><div><strong>'+game.kills+'</strong><small>HOSTILES SUNK</small></div><div><strong>'+fmt(game.time)+'</strong><small>TIME SUBMERGED</small></div></div>'+(campaignBonus?'<p class="campaign-bonus">FIRST CLEAR / +'+campaignBonus+' BONUS SILVER · NEW ROUTES CHARTED</p>':'')+'<p>Class '+game.tier+' · Level '+game.level+' · '+game.chestsOpened+' vaults · '+game.bosses+' guardians defeated</p>';
 if(earnedAchievements.length){const rewards=document.createElement('div');rewards.className='achievement-unlocks';for(const a of earnedAchievements){const row=document.createElement('div');const title=document.createElement('strong');title.textContent='✦ '+a.name;const detail=document.createElement('span');detail.textContent=a.rewardText||a.rewardLabel||a.desc||'Unique shipyard gear unlocked';row.append(title,detail);rewards.append(row);}$('modal-info').append(rewards);action('VIEW ACHIEVEMENTS',()=>{home();showHarbor('achievements');});}
 if(mission){const missionId=game.missionId;action('RETURN TO SEA CHART',openAtlas,true);action(won?'REPLAY THIS MISSION':'RETRY THIS MISSION',()=>start(true,missionId));action('RETURN TO SHIPYARD',()=>{openAtlas();showResearch();});}
 else {action('RETURN TO SEA CHART',openAtlas,true);action('DESCEND AGAIN',()=>start(true));action('RETURN TO SHIPYARD',()=>{home();showResearch();});}
 action('HARBOR',home);focusModal();wasState=game.state;
}
function buy(){if(game?.state==='playing'&&game.gold>=game.upgradePrice()){game.openDraft('upgrade');showDraft();wasState='draft';}}
$('shop-open').onclick=()=>showHarbor('shop');$('customize-open').onclick=()=>showHarbor('customize');$('achievements-open').onclick=()=>showHarbor('achievements');
$('controls-open').onclick=()=>{if(!game||['playing','paused'].includes(game.state))showControls(modalKind==='pause'?'pause':'header');};$('dive').onclick=openAtlas;$('resume-run').onclick=resumeRun;$('pressure-select').onclick=()=>selectLoadout('pressure');$('captain-select').onclick=()=>selectLoadout('captain');$('crew-select').onclick=()=>selectLoadout('crew');$('weapon-select').onclick=()=>selectLoadout('weapon');$('shipyard-open').onclick=showResearch;$('collection-open').onclick=showArchive;$('pause').onclick=pause;$('help').onclick=()=>{if(!game||game.state==='playing')help();};$('sound').onclick=()=>{sound.toggle();$('sound').textContent=sound.enabled?'SOUND ON':'SOUND OFF';try{localStorage.setItem('underburg.sound',sound.enabled?'on':'off');}catch{}};$('sonar').onclick=()=>game?.pulse();$('buy-upgrade').onclick=buy;
$('boost').addEventListener('pointerdown',e=>{boostHeld=true;$('boost').setPointerCapture(e.pointerId);});for(const type of ['pointerup','pointercancel'])$('boost').addEventListener(type,()=>boostHeld=false);
const canvas=$('ocean');canvas.addEventListener('pointerdown',e=>{if(game?.state!=='playing')return;pointer={id:e.pointerId,sx:e.clientX,sy:e.clientY,x:e.clientX,y:e.clientY};canvas.setPointerCapture(e.pointerId);sound.start();});canvas.addEventListener('pointermove',e=>{if(pointer?.id===e.pointerId){pointer.x=e.clientX;pointer.y=e.clientY;}});for(const type of ['pointerup','pointercancel'])canvas.addEventListener(type,()=>pointer=null);canvas.addEventListener('wheel',e=>{if(atlas?.active)return;e.preventDefault();view?.setZoom(e.deltaY*.0005);},{passive:false});canvas.addEventListener('contextmenu',e=>e.preventDefault());
addEventListener('keydown',e=>{
 if(modalKind==='controls'){
  if(captureBinding(e))return;
  if(e.code==='Escape'&&!e.repeat){e.preventDefault();e.stopImmediatePropagation();controlsExit?.();}return;
 }
 if(e.target instanceof HTMLElement&&e.target.closest('input,textarea,select,[contenteditable="true"]'))return;
 if(e.ctrlKey||e.metaKey||e.altKey)return;
 if(e.code==='KeyM'&&!e.repeat)$('sound').click();
 if(harborUI?.active){if(e.code==='Escape'&&!e.repeat){e.preventDefault();if(modalKind)closeModal();else closeHarbor();}return;}
 if(atlas?.active){if(modalKind&&e.code==='Escape'&&!e.repeat){e.preventDefault();e.stopImmediatePropagation();closeModal();}return;}
 if(e.code==='Escape'&&!e.repeat){if(game&&['playing','paused'].includes(game.state)){if(modalKind==='help'){closeModal();game.state='playing';}else pause();}else if(!game)closeModal();}
 if(game?.state!=='playing')return;
 if(['Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.code)||bindings.includes(e.code)||/^Digit[1-6]$/.test(e.code))e.preventDefault();
 keys.add(e.code);
 if(!e.repeat){
  if(e.code==='Space')game.pulse();
  const slot=/^Digit[1-6]$/.test(e.code)?Number(e.code.slice(-1))-1:bindings.slice(0,6).indexOf(e.code);
  if(slot>=0)game.activate(slot);
  if(e.code===bindings[6])for(let i=0;i<game.moduleOrder.length;i++)game.activate(i);
  if(e.code==='KeyB')buy();
 }
});addEventListener('keyup',e=>keys.delete(e.code));addEventListener('blur',()=>{keys.clear();pointer=null;boostHeld=false;if(game?.state==='playing')pause();});document.addEventListener('visibilitychange',()=>{if(document.hidden&&game?.state==='playing')pause();});
addEventListener('pagehide',checkpoint);
$('modal').addEventListener('keydown',e=>{if(e.key!=='Tab')return;const all=[...$('modal').querySelectorAll('button:not(:disabled)')].filter(b=>b.tabIndex!==-1);if(!all.length)return;if(e.shiftKey&&document.activeElement===all[0]){e.preventDefault();all.at(-1).focus();}else if(!e.shiftKey&&document.activeElement===all.at(-1)){e.preventDefault();all[0].focus();}});
function handleEvent(e){view.event(e);sound.event(e);if(e.type==='discovery'){toast('CHARTED / '+e.name+' · +'+e.gold+' GOLD · Vault revealed',6);flash('#a6dfca');}if(e.type==='evolution'){syncModules();toast(EVOLUTIONS[e.key].find(x=>x.id===e.evolution).name.toUpperCase()+' / EVOLUTION INSTALLED',5);flash('#e8c58b');}if(e.type==='level'){toast('CITADEL LEVEL '+e.level+(e.level%4===1?' / YOUR FORTRESS HAS GROWN':''));flash();}if(e.type==='installed'){syncModules();toast(WEAPONS[e.key].name+' installed · press '+bindingLabel(bindings[game.moduleOrder.indexOf(e.key)])+' for its active ability.');}if(e.type==='artifact'){syncArtifacts();toast(ARTIFACTS[e.key].name+' recovered'+(e.factor>1?' · '+e.factor.toFixed(2)+'× STRENGTH':''));}if(e.type==='rarity'&&e.rarity==='universe'){toast('UNIVERSE SIGNAL / Reality-class engineering',6);flash('#ca9bf3');}if(e.type==='upgrade'){syncModules();toast(WEAPONS[e.key].name+' improved · '+RARITIES[e.rarity].name);}if(e.type==='boss')toast('SONAR CONTACT'+(Number.isInteger(e.wave)?' / BOSS '+(e.wave+1)+' OF 3':'')+': '+e.name.toUpperCase(),6);if(e.type==='bossDefeated'){toast(e.defeated+' / 3 GUARDIANS DEFEATED'+(e.defeated<3?' · Hull repaired · Artifact recovered':' · SEA LANE SECURED'),6);flash('#a2e0c0');}if(e.type==='eliteIncoming')toast('An armored salvage hunter has entered these waters.');if(e.type==='overtime')toast('PRESSURE SURGE · Enemy engines are accelerating.',6);if(e.type==='jackpot')toast('HANSE DIVIDEND · +'+e.value+' GOLD');if(e.type==='revive'){toast('ABGRUNDHERZ SHATTERED · A second chance.',6);flash('#e5c185');}if(e.type==='reset')toast('JÄGERUHR · All active systems recharged.');}
function frame(ms){const dt=Math.min(.05,(ms-last)/1000||0);last=ms;elapsed+=dt;if(game&&!atlas?.active&&!harborUI?.active){let x=(keys.has('KeyD')||keys.has('ArrowRight')?1:0)-(keys.has('KeyA')||keys.has('ArrowLeft')?1:0),y=(keys.has('KeyS')||keys.has('ArrowDown')?1:0)-(keys.has('KeyW')||keys.has('ArrowUp')?1:0);if(pointer){x=clamp((pointer.x-pointer.sx)/45,-1,1);y=clamp((pointer.y-pointer.sy)/45,-1,1);}game.update(dt,{x,y,boost:boostHeld||keys.has('ShiftLeft')||keys.has('ShiftRight')});for(const e of game.events.splice(0))handleEvent(e);if(game.state!==wasState||(game.state==='draft'&&modalKind!=='draft')){if(game.state==='draft')showDraft();if(game.state==='sector')showSector();if(game.state==='won'||game.state==='lost')showEnd();wasState=game.state;checkpoint();}if(elapsed>=saveAt)checkpoint();hudT-=dt;if(hudT<=0){syncHud();hudT=.1;}if(elapsed>toastUntil)$('toast').style.opacity='0';}if(atlas?.active)atlas.update(dt);else view?.update(dt,game);harborUI?.update?.(dt);sound.update(game);requestAnimationFrame(frame);}
save();updateMenu();try{view=new OceanView(canvas,(ready,error,progress)=>{if(error){$('loading-error').classList.remove('hidden');$('loading-error').textContent='The 3D renderer could not load. '+error.message+' Refresh this page after starting the local server with node serve.cjs.';$('load-label').textContent='3D ASSETS UNAVAILABLE';return;}if(progress)$('load-label').textContent='ASSEMBLING THE FLEET / '+Math.round(progress*100)+'%';if(ready){$('dive').disabled=false;$('load-label').textContent='CHART YOUR COURSE';view.setMenuHull(selected.hull,H.getLoadout(harborState));harborUI=new Harbor({view,getHull:()=>selected.hull,onChange:(state)=>{if(state)harborState=state;save();updateMenu();},onEquip:applyLook,onClose:closeHarbor,sound});atlas=new Atlas({view,onLaunch:id=>start(false,id),onHarbor:home,onShipyard:showResearch,onDock:()=>showHarbor('shop'),onSelectSound:()=>{sound.start();sound.tone(294,.2,'sine',.035,440);},onChange:save});if(new URLSearchParams(location.search).get('screen')==='atlas')openAtlas();}});requestAnimationFrame(frame);}catch(e){$('loading-error').classList.remove('hidden');$('loading-error').textContent='Ünderburg requires WebGL. Enable hardware acceleration in your browser and reload. '+e.message;}
window.__underburg={get state(){if(harborUI?.active)return {state:'harbor',ready:!view?.loading,metaSilver:meta.silver,tab:harborUI.tab};if(atlas?.active)return {state:'atlas',ready:!view?.loading,metaSilver:meta.silver,atlas:JSON.parse(JSON.stringify(atlas.state))};return game?{state:game.state,missionId:game.missionId||null,time:game.time,stage:game.stage,level:game.level,tier:game.tier,hp:game.p.hp,x:game.p.x,y:game.p.y,gold:game.gold,silver:game.silver,kills:game.kills,enemies:game.enemies.length,modules:game.moduleOrder.slice(),artifacts:game.artifacts.map(a=>a.key),chests:game.chestsOpened,bossProgress:game.bossProgress?{...game.bossProgress}:null}: {state:'menu',ready:!view?.loading,metaSilver:meta.silver};},get atlas(){return atlas?JSON.parse(JSON.stringify(atlas.state)):null;},get campaign(){return JSON.parse(JSON.stringify(campaign));},get harbor(){return JSON.parse(JSON.stringify(harborState));},get renderStats(){return view?.stats;}};
