import * as THREE from './assets/lib/three.module.js';
const vertex='varying vec2 vUv;void main(){vUv=uv;gl_Position=vec4(position.xy,0.,1.);}';
/** Small HDR bloom pass. Geometry and targets are allocated once and reused. */
export class OceanPost{
 constructor(renderer){this.renderer=renderer;this.size=new THREE.Vector2();const hdr=renderer.capabilities.isWebGL2&&renderer.extensions.has('EXT_color_buffer_float');this.enabled=hdr;this.target=new THREE.WebGLRenderTarget(1,1,{type:hdr?THREE.HalfFloatType:THREE.UnsignedByteType,depthBuffer:true});this.target.samples=renderer.capabilities.isWebGL2?Math.min(2,renderer.capabilities.maxSamples):0;this.bright=new THREE.WebGLRenderTarget(1,1,{type:hdr?THREE.HalfFloatType:THREE.UnsignedByteType,depthBuffer:false});this.blur=this.bright.clone();this.scene=new THREE.Scene();this.camera=new THREE.Camera();this.quad=new THREE.Mesh(new THREE.PlaneGeometry(2,2));this.quad.frustumCulled=false;this.scene.add(this.quad);
  this.extract=new THREE.ShaderMaterial({vertexShader:vertex,fragmentShader:'varying vec2 vUv;uniform sampler2D source;void main(){vec3 c=texture2D(source,vUv).rgb;float l=max(c.r,max(c.g,c.b));gl_FragColor=vec4(c*smoothstep(.95,2.4,l),1.);}',uniforms:{source:{value:this.target.texture}},depthTest:false,depthWrite:false,toneMapped:false});
  this.horizontal=new THREE.ShaderMaterial({vertexShader:vertex,fragmentShader:'varying vec2 vUv;uniform sampler2D source;uniform vec2 texel;void main(){vec3 c=texture2D(source,vUv).rgb*.227027;c+=(texture2D(source,vUv+vec2(texel.x*1.384615,0.)).rgb+texture2D(source,vUv-vec2(texel.x*1.384615,0.)).rgb)*.316216;c+=(texture2D(source,vUv+vec2(texel.x*3.230769,0.)).rgb+texture2D(source,vUv-vec2(texel.x*3.230769,0.)).rgb)*.070270;gl_FragColor=vec4(c,1.);}',uniforms:{source:{value:this.bright.texture},texel:{value:new THREE.Vector2()}},depthTest:false,depthWrite:false,toneMapped:false});
  this.combine=new THREE.ShaderMaterial({vertexShader:vertex,fragmentShader:`varying vec2 vUv;uniform sampler2D source;uniform sampler2D bloom;uniform vec2 texel;uniform float glow;
  void main(){vec3 c=texture2D(source,vUv).rgb;vec3 b=texture2D(bloom,vUv).rgb*.227027;b+=(texture2D(bloom,vUv+vec2(0.,texel.y*1.384615)).rgb+texture2D(bloom,vUv-vec2(0.,texel.y*1.384615)).rgb)*.316216;b+=(texture2D(bloom,vUv+vec2(0.,texel.y*3.230769)).rgb+texture2D(bloom,vUv-vec2(0.,texel.y*3.230769)).rgb)*.070270;gl_FragColor=vec4(c+b*glow,1.);
  #include <tonemapping_fragment>
  #include <colorspace_fragment>
  }`,uniforms:{source:{value:this.target.texture},bloom:{value:this.blur.texture},texel:{value:new THREE.Vector2()},glow:{value:.2}},depthTest:false,depthWrite:false,toneMapped:true});this.resize();
 }
 resize(){if(!this.enabled)return;this.renderer.getDrawingBufferSize(this.size);const w=this.size.x,h=this.size.y;this.target.setSize(w,h);this.bright.setSize(Math.max(1,w>>1),Math.max(1,h>>1));this.blur.setSize(Math.max(1,w>>1),Math.max(1,h>>1));this.horizontal.uniforms.texel.value.set(2/w,2/h);this.combine.uniforms.texel.value.set(2/w,2/h);}
 render(scene,camera){const r=this.renderer;if(!this.enabled){r.setRenderTarget(null);r.render(scene,camera);this.stats={calls:r.info.render.calls,triangles:r.info.render.triangles};return;}r.setRenderTarget(this.target);r.render(scene,camera);const calls=r.info.render.calls,triangles=r.info.render.triangles;r.setRenderTarget(this.bright);this.quad.material=this.extract;r.render(this.scene,this.camera);r.setRenderTarget(this.blur);this.quad.material=this.horizontal;r.render(this.scene,this.camera);r.setRenderTarget(null);this.quad.material=this.combine;r.render(this.scene,this.camera);this.stats={calls:calls+3,triangles:triangles+6};}
}
