import * as THREE from './assets/lib/three.module.js';
const TAU=Math.PI*2;
const hash=n=>{let x=Math.sin(n*127.1+311.7)*43758.5453;return x-Math.floor(x);};
const height=(x,z,stage)=>window.UBWorld?.heightAt(x,z,stage)??-1;
const MIX=new THREE.Color();
export const OCEAN_PALETTES=[
 {water:0x164c57,deep:0x17484a,sand:0x789889,reef:0x386d60,shaft:0xb4efcf,glow:0x64efcb},
 {water:0x173d4b,deep:0x203a45,sand:0x64766c,reef:0x414e50,shaft:0xb7ced0,glow:0xf0b364},
 {water:0x111f39,deep:0x172535,sand:0x42495b,reef:0x2c3a52,shaft:0x97afdc,glow:0x75c9ff}
];

/** A world anchored to map coordinates: no camera-snapped scenery or changing routes. */
export class OceanWorld {
 constructor(view){this.view=view;this.scene=view.scene;this.root=new THREE.Group();this.root.name='charted-seabed';this.scene.add(this.root);this.stage=-1;this.seed=0;this.landmarks=[];this.groups=[];this.deco=[];this.bubbles=[];this.visibleDecor=0;this.lastCull=new THREE.Vector2(Infinity,Infinity);this.dummy=new THREE.Object3D();this.matrix=new THREE.Matrix4();this.clock=0;this.buildFloor();this.buildShafts();this.buildMotes();}
 buildFloor(){
  const geo=new THREE.PlaneGeometry(960,960,240,240);geo.rotateX(-Math.PI/2);geo.setAttribute('color',new THREE.BufferAttribute(new Float32Array(geo.attributes.position.count*3),3));
  const c=document.createElement('canvas');c.width=c.height=512;const ctx=c.getContext('2d'),pixels=ctx.createImageData(512,512);for(let y=0;y<512;y++)for(let x=0;x<512;x++){const i=(y*512+x)*4;const ripple=Math.sin(y*.19+Math.sin(x*.018)*2.5)*3,n=hash(x+y*512)*15;pixels.data[i]=166+n+ripple;pixels.data[i+1]=176+n+ripple;pixels.data[i+2]=162+n+ripple;pixels.data[i+3]=255;}ctx.putImageData(pixels,0,0);const map=new THREE.CanvasTexture(c);map.colorSpace=THREE.SRGBColorSpace;map.wrapS=map.wrapT=THREE.RepeatWrapping;map.repeat.set(40,40);
  this.floor=new THREE.Mesh(geo,new THREE.MeshStandardMaterial({vertexColors:true,map,roughness:.98,metalness:.01}));this.floor.receiveShadow=true;this.floor.name='sculpted-seafloor';this.root.add(this.floor);
  this.caustic=new THREE.Mesh(geo.clone(),new THREE.ShaderMaterial({uniforms:{time:{value:0},strength:{value:.13},tint:{value:new THREE.Color(0x8bd7b1)}},vertexShader:'varying vec3 pos;void main(){pos=position;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}',fragmentShader:`uniform float time;uniform float strength;uniform vec3 tint;varying vec3 pos;
  void main(){vec2 p=pos.xz*.65;float a=sin(p.x+sin(p.y*.82+time*.23)*1.8+time*.14);float b=cos(p.y*.92+cos(p.x*.71-time*.17)*1.9);float line=pow(max(0.,1.-abs(a+b)*2.8),8.);float patches=.32+.68*smoothstep(-.4,.7,sin(pos.x*.038+pos.z*.021));gl_FragColor=vec4(tint,line*strength*patches);}`,transparent:true,depthWrite:false,blending:THREE.AdditiveBlending}));this.caustic.position.y=.018;this.root.add(this.caustic);
  // A dark escarpment outside the navigable area gives the seabed a distant silhouette.
  const edgeGeo=new THREE.RingGeometry(250,290,128,3);edgeGeo.rotateX(-Math.PI/2);this.rim=new THREE.Mesh(edgeGeo,new THREE.MeshStandardMaterial({color:0x0d2b32,roughness:1,side:THREE.DoubleSide}));this.rim.position.y=-3;this.rim.visible=false;this.root.add(this.rim);
 }
 buildShafts(){
  const c=document.createElement('canvas');c.width=64;c.height=256;const x=c.getContext('2d'),data=x.createImageData(64,256);for(let y=0;y<256;y++)for(let i=0;i<64;i++){const u=(i/63-.5)*2,v=y/255,width=.15+v*.8;const a=Math.exp(-Math.pow(u/width,2)*5)*Math.sin(v*Math.PI)*.55;const n=(y*64+i)*4;data.data[n]=data.data[n+1]=data.data[n+2]=255;data.data[n+3]=a*255;}x.putImageData(data,0,0);this.shaftMap=new THREE.CanvasTexture(c);
  this.shafts=[];const geometry=new THREE.PlaneGeometry(15,75);this.shaftMaterial=new THREE.MeshBasicMaterial({map:this.shaftMap,color:0xb4efcf,transparent:true,opacity:.16,depthWrite:false,side:THREE.DoubleSide,blending:THREE.AdditiveBlending});for(let i=0;i<35;i++){const o=new THREE.Mesh(geometry,this.shaftMaterial);o.position.set((hash(i+38)-.5)*480,24,(hash(i+79)-.5)*480);o.userData.phase=hash(i)*TAU;this.root.add(o);this.shafts.push(o);}
 }
 buildMotes(){const geometry=new THREE.SphereGeometry(.05,5,4);this.ventBubbles=new THREE.InstancedMesh(geometry,new THREE.MeshBasicMaterial({color:0xb7e8e0,transparent:true,opacity:.24,depthWrite:false}),180);this.ventBubbles.instanceMatrix.setUsage(THREE.DynamicDrawUsage);this.ventBubbles.frustumCulled=false;this.ventBubbles.count=0;this.root.add(this.ventBubbles);}
 clearRegion(){
  for(const g of this.groups){this.root.remove(g.mesh);g.mesh.dispose();if(g.ownedMaterial)g.mesh.material.dispose();}this.groups=[];this.deco=[];
  for(const o of this.landmarks){this.root.remove(o);this.view.release(o);}this.landmarks=[];this.bubbles=[];this.lastCull.set(Infinity,Infinity);
 }
 setRegion(stage,seed,landmarkDefs,menu=false){
  const key=stage+'|'+seed+'|'+menu;if(this.key===key)return;this.key=key;this.stage=stage;this.seed=seed;this.menu=menu;this.clearRegion();const palette=OCEAN_PALETTES[stage],geo=this.floor.geometry,positions=geo.attributes.position,colors=geo.attributes.color;const deep=new THREE.Color(palette.deep),sand=new THREE.Color(palette.sand),reef=new THREE.Color(palette.reef);
  for(let i=0;i<positions.count;i++){const x=positions.getX(i),z=positions.getZ(i),h=height(x,z,stage)-Math.max(0,Math.max(Math.abs(x),Math.abs(z))-250)*.07;positions.setY(i,h);const dune=.5+.5*Math.sin(x*.043+Math.sin(z*.034)*2.3),patch=.5+.5*Math.cos(z*.063+Math.sin(x*.059));MIX.copy(deep).lerp(sand,Math.max(.08,Math.min(.87,(h+6)/6))*(.45+dune*.35));MIX.lerp(reef,patch*.24);MIX.multiplyScalar(.91+hash(i+stage*779)*.1);colors.setXYZ(i,MIX.r,MIX.g,MIX.b);}positions.needsUpdate=true;colors.needsUpdate=true;geo.computeVertexNormals();geo.computeBoundingSphere();this.caustic.geometry.attributes.position.array.set(positions.array);this.caustic.geometry.attributes.position.needsUpdate=true;this.caustic.geometry.computeBoundingSphere();this.caustic.material.uniforms.strength.value=[.045,.025,.012][stage];this.caustic.material.uniforms.tint.value.setHex(palette.glow);this.shaftMaterial.color.setHex(palette.shaft);this.shaftMaterial.opacity=[.2,.1,.065][stage];
  const landmarks=menu?[
   {id:'harbor',name:'Glockenhafen',model:'world-bell-tower',x:-320,y:-320,rotation:-.2,scale:1},
   {id:'dome',name:'Nautisches Institut',model:'world-observatory',x:520,y:-290,rotation:.3,scale:1},
   {id:'gate',name:'Altes Tor',model:'world-arch',x:470,y:430,rotation:.6,scale:1.15}
  ]:landmarkDefs||[];
  this.landmarkDefs=landmarks;
  for(const d of landmarks){const o=this.view.clone(d.model,true);o.name=d.id;o.position.set(d.x*.1,height(d.x*.1,d.y*.1,stage),d.y*.1);o.rotation.y=d.rotation||0;o.scale.setScalar(d.scale||1);this.root.add(o);this.landmarks.push(o);if(d.model.includes('basalt')||d.model.includes('pipeline'))this.bubbles.push({x:d.x*.1,z:d.y*.1});}
  const points=[];const salt=seed%65521+stage*195;
  const allowed=(x,z)=>Math.hypot(x,z)>12&&(!menu||Math.hypot(x-17,z)>20)&&landmarks.every(l=>Math.hypot(x-l.x*.1,z-l.y*.1)>(l.solidRadius||95)*.1+4&&(!l.courtyard||Math.hypot(x-l.courtyard.x*.1,z-l.courtyard.y*.1)>9));
  const add=(name,x,z,scale,rotation)=>{if(allowed(x,z))points.push({name,x,z,scale,rotation,phase:hash(points.length+43)*TAU});};
  // Irregular, anchored outcrops and narrow forests; open sand is the main movement space.
  for(let i=0;i<520;i++){const x=(hash(i*13+salt)-.5)*506,z=(hash(i*23+salt+88)-.5)*506;const pocket=Math.sin(x*.037)+Math.cos(z*.031+x*.009);let name=stage===0?(i%4===0?'coral':i%3===0?'fan':i%2?'rock-a':'rock-b'):stage===1?(i%7===0?'wreck':i%4===0?'vent':i%2?'rock-a':'rock-b'):(i%7===0?'world-crystal':i%5===0?'vent':i%2?'rock-a':'rock-b');const scale=name==='world-crystal'?.22+hash(i+19)*.25:name==='wreck'?.5+hash(i)*.5:.65+hash(i+21)*1.5;if(pocket>-.75)add(name,x,z,scale,hash(i+77)*TAU);}
  for(let cluster=0;cluster<90;cluster++){const cx=(hash(cluster*7+salt+200)-.5)*480,cz=(hash(cluster*17+salt+450)-.5)*480;if(Math.sin(cx*.037)+Math.cos(cz*.031+cx*.009)<-.8)continue;const count=stage===0?13:stage===1?5:4;for(let j=0;j<count;j++){const a=hash(cluster*41+j+89)*TAU,r=2+hash(j*43+cluster+42)*8;const name=stage===0?(j%7===0?'world-anemone':'kelp'):stage===1?(j%4===0?'coral':'kelp'):(j%3===0?'world-crystal':'fan');const scale=name.startsWith('world-')?.15+hash(j+cluster)*.13:.45+hash(j*61+cluster)*.85;add(name,cx+Math.cos(a)*r,cz+Math.sin(a)*r,scale,hash(j+95)*TAU);}}
  // Hand-placed harbor vegetation frames the first few seconds of play.
  for(let i=0;i<38;i++){const a=i*2.4,r=22+hash(i+salt)*40;add(stage===2?'world-crystal':i%3?'kelp':'coral',Math.cos(a)*r,Math.sin(a)*r,stage===2?.2:.7+hash(i)*.8,a);}
  this.deco=points;
  for(const name of new Set(points.map(p=>p.name))){const asset=this.view.assets[name];if(!asset)continue;asset.updateMatrixWorld(true);const list=points.filter(p=>p.name===name);asset.traverse(part=>{if(!part.isMesh)return;const plant=['kelp','fan','coral','world-anemone'].includes(name),mat=plant?part.material.clone():part.material;if(plant){mat.onBeforeCompile=shader=>{shader.uniforms.oceanTime={value:0};mat.userData.shader=shader;shader.vertexShader='uniform float oceanTime;\n'+shader.vertexShader;shader.vertexShader=shader.vertexShader.replace('#include <begin_vertex>','#include <begin_vertex>\nfloat bend=pow(max(0.,position.y),1.25)*.024; transformed.x+=sin(oceanTime*.8+instanceMatrix[3].x*.14+instanceMatrix[3].z*.09)*bend;');};mat.customProgramCacheKey=()=> 'underburg-kelp-sway';}const mesh=new THREE.InstancedMesh(part.geometry,mat,Math.min(list.length,900));mesh.instanceMatrix.setUsage(THREE.DynamicDrawUsage);mesh.frustumCulled=false;mesh.receiveShadow=true;mesh.castShadow=false;mesh.count=0;this.root.add(mesh);this.groups.push({mesh,points:list,base:part.matrixWorld.clone(),name,ownedMaterial:plant});});}
  for(let i=0;i<12;i++)this.bubbles.push({x:(hash(i+salt+880)-.5)*440,z:(hash(i+salt+960)-.5)*440});this.cull(0,0,true);
 }
 cull(x,z,force=false){const extentX=Math.max(65,Math.abs(this.view.camera.right)+26),extentZ=Math.max(75,Math.abs(this.view.camera.top)*1.4+32),extentKey=extentX+'/'+extentZ;if(!force&&extentKey===this.extentKey&&this.lastCull.distanceToSquared(new THREE.Vector2(x,z))<16)return;this.extentKey=extentKey;this.extents={x:extentX,z:extentZ};this.lastCull.set(x,z);let total=0;for(const g of this.groups){let count=0;for(const p of g.points){if(Math.abs(p.x-x)>extentX||Math.abs(p.z-z)>extentZ)continue;if(count>=g.mesh.instanceMatrix.count)break;this.dummy.position.set(p.x,height(p.x,p.z,this.stage),p.z);this.dummy.rotation.set(0,p.rotation,0);this.dummy.scale.setScalar(p.scale);this.dummy.updateMatrix();this.matrix.multiplyMatrices(this.dummy.matrix,g.base);g.mesh.setMatrixAt(count++,this.matrix);}g.mesh.count=count;g.mesh.instanceMatrix.needsUpdate=true;total+=count;}this.visibleDecor=total;}
 update(dt,focus,camera,game){this.clock+=dt;this.caustic.material.uniforms.time.value=this.clock;for(const g of this.groups)if(g.ownedMaterial&&g.mesh.material.userData.shader)g.mesh.material.userData.shader.uniforms.oceanTime.value=this.clock;this.cull(focus.x,focus.z);for(const o of this.landmarks)o.visible=Math.hypot(o.position.x-focus.x,o.position.z-focus.z)<155;for(const s of this.shafts){const d=Math.hypot(s.position.x-focus.x,s.position.z-focus.z);s.visible=d<125;if(s.visible){s.quaternion.copy(camera.quaternion);s.rotateZ(-.23+Math.sin(this.clock*.12+s.userData.phase)*.015);}}
  let n=0;for(const b of this.bubbles){if(Math.hypot(b.x-focus.x,b.z-focus.z)>90)continue;for(let i=0;i<10;i++){const t=(this.clock*.32+i*.37)%4,y=height(b.x,b.z,this.stage)+t*4;this.dummy.position.set(b.x+Math.sin(t+i)*.45,y,b.z+Math.cos(i*3+t)*.4);this.dummy.scale.setScalar(.6+t*.24);this.dummy.rotation.set(0,0,0);this.dummy.updateMatrix();this.ventBubbles.setMatrixAt(n++,this.dummy.matrix);}}this.ventBubbles.count=n;this.ventBubbles.instanceMatrix.needsUpdate=true;
 }
 get stats(){return {landmarks:this.landmarks.length,anchoredDecor:this.deco.length,visibleInstances:this.visibleDecor,rootChildren:this.root.children.length,cullExtents:this.extents,floorHalfExtent:480,stage:this.stage};}
}
