import * as THREE from './assets/lib/three.module.js';
import {GLTFLoader} from './assets/lib/GLTFLoader.js';
import {OceanWorld,OCEAN_PALETTES} from './ocean-world.js';
import {OceanPost} from './ocean-post.js';
import {applyLivery,appearanceKey} from './ship-livery.js';
import {CombatFX} from './combat-fx.js';
import {ShipAssembly} from './ship-growth.js';
import {ImpactFX} from './impact-fx.js';
import {GuardianFX} from './guardian-fx.js';
const S=.1,TAU=Math.PI*2,hash=n=>{const x=Math.sin(n*127.1+311.7)*43758.5453;return x-Math.floor(x);};
const palette={gold:0xffc86f,mint:0x91ffda,red:0xff876b,ice:0x9feaff,violet:0xbf9fff};
function radialTexture(){const c=document.createElement('canvas');c.width=c.height=64;const x=c.getContext('2d'),g=x.createRadialGradient(32,32,0,32,32,32);g.addColorStop(0,'rgba(255,255,255,1)');g.addColorStop(.15,'rgba(255,255,255,.8)');g.addColorStop(.45,'rgba(255,255,255,.2)');g.addColorStop(1,'rgba(255,255,255,0)');x.fillStyle=g;x.fillRect(0,0,64,64);return new THREE.CanvasTexture(c);}
function seabedHeight(x,z,stage=0){return window.UBWorld?.heightAt(x,z,stage)??-1;}
export class OceanView{
 constructor(canvas,onLoad=()=>{}){
  this.canvas=canvas;this.motionQuery=matchMedia('(prefers-reduced-motion: reduce)');this.reducedMotion=this.motionQuery.matches;this.graphicsOptions={quality:'balanced',distortion:true};this.motionQuery.addEventListener('change',e=>{this.reducedMotion=e.matches;this.post?.configure({...this.graphicsOptions,reducedMotion:this.reducedMotion});if(this.reducedMotion)this.shake=0;});this.renderer=new THREE.WebGLRenderer({canvas,antialias:true,alpha:false,powerPreference:'high-performance'});this.renderer.setPixelRatio(Math.min(devicePixelRatio||1,1.5));this.renderer.setSize(innerWidth,innerHeight);this.renderer.outputColorSpace=THREE.SRGBColorSpace;this.renderer.toneMapping=THREE.ACESFilmicToneMapping;this.renderer.toneMappingExposure=1.18;this.renderer.shadowMap.enabled=true;this.renderer.shadowMap.type=THREE.PCFSoftShadowMap;
  this.scene=new THREE.Scene();this.scene.background=new THREE.Color(0x133c4a);this.scene.fog=new THREE.FogExp2(0x153e4a,.0038);this.camera=new THREE.OrthographicCamera(-60,60,40,-40,.1,650);this.camera.position.set(0,100,95);this.target=new THREE.Vector3();this.camera.lookAt(this.target);this.clock=0;this.assets={};this.assetSizes={};this.entities=new Map();this.props=new Map();this.bullets=new Map();this.fx=[];this.damageTexts=[];this.shake=0;this.stage=-1;this.focus=new THREE.Vector3();this.loading=true;this.onLoad=onLoad;this.thumbnails=new Map();this.menuHull='nautilus';this.menuModel=null;this.shipSignature='';this.game=null;this.ambient=[];this.zoom=1;this.lastDeco={x:Infinity,z:Infinity};
  this.lightTexture=radialTexture();this.setupLighting();this.setupSea();this.setupResources();this.setupAtmosphere();this.combatFX=new CombatFX(this);this.impactFX=new ImpactFX(this);this.guardianFX=new GuardianFX(this);this.post=new OceanPost(this.renderer);this.post.configure({...this.graphicsOptions,reducedMotion:this.reducedMotion});this.resize();addEventListener('resize',()=>this.resize());
  this.ready=this.loadAssets().then(()=>{this.loading=false;this.setupEnvironment();this.setMenuHull('nautilus');onLoad(true);}).catch(e=>{console.error(e);this.error=e;onLoad(false,e);});
 }
 setupLighting(){
  this.hemi=new THREE.HemisphereLight(0xb4ecd6,0x092232,1.65);this.scene.add(this.hemi);this.sun=new THREE.DirectionalLight(0xffe1af,3.6);this.sun.position.set(-40,85,15);this.sun.castShadow=true;this.sun.shadow.mapSize.set(2048,2048);Object.assign(this.sun.shadow.camera,{left:-70,right:70,top:70,bottom:-70,near:1,far:220});this.sun.shadow.bias=-.001;this.sun.shadow.normalBias=.12;this.scene.add(this.sun);this.scene.add(this.sun.target);
  const fill=new THREE.DirectionalLight(0x5bbabf,1.05);fill.position.set(25,20,-40);this.scene.add(fill);this.fill=fill;
  const faces=[];for(let i=0;i<6;i++){const c=document.createElement('canvas');c.width=c.height=32;const x=c.getContext('2d'),g=x.createLinearGradient(0,0,0,32);g.addColorStop(0,i===2?'#c3dac2':'#456b6e');g.addColorStop(.5,'#365454');g.addColorStop(1,'#152d38');x.fillStyle=g;x.fillRect(0,0,32,32);faces.push(c);}this.environment=new THREE.CubeTexture(faces);this.environment.needsUpdate=true;this.environment.colorSpace=THREE.SRGBColorSpace;this.scene.environment=this.environment;
 }
 setupSea(){this.worldView=new OceanWorld(this);this.floor=this.worldView.floor;this.caustics=this.worldView.caustic;}
 setupResources(){const goldGeo=new THREE.IcosahedronGeometry(.32,0);this.gold=new THREE.InstancedMesh(goldGeo,new THREE.MeshStandardMaterial({color:0xffcf74,metalness:.65,roughness:.23,emissive:0x986220,emissiveIntensity:.6}),760);this.gold.instanceMatrix.setUsage(THREE.DynamicDrawUsage);this.gold.count=0;this.gold.frustumCulled=false;this.scene.add(this.gold);this.dummy=new THREE.Object3D();
  const bubbleGeo=new THREE.BufferGeometry(),pos=new Float32Array(750*3);for(let i=0;i<750;i++){pos[i*3]=(hash(i*7)-.5)*240;pos[i*3+1]=hash(i*19)*45;pos[i*3+2]=(hash(i*11)-.5)*180;}bubbleGeo.setAttribute('position',new THREE.BufferAttribute(pos,3));this.plankton=new THREE.Points(bubbleGeo,new THREE.PointsMaterial({map:this.lightTexture,color:0xa8e4d5,size:.15,transparent:true,opacity:.35,depthWrite:false,blending:THREE.AdditiveBlending}));this.scene.add(this.plankton);
 }
 setupAtmosphere(){const fishGeo=new THREE.ConeGeometry(.23,1.1,4);fishGeo.rotateZ(-Math.PI/2);this.fish=new THREE.InstancedMesh(fishGeo,new THREE.MeshStandardMaterial({color:0x9eccc0,metalness:.3,roughness:.5}),100);this.fish.instanceMatrix.setUsage(THREE.DynamicDrawUsage);this.fish.frustumCulled=false;this.scene.add(this.fish);}
 async loadAssets(){const loader=new GLTFLoader();const names=['nautilus','bastion','wraith','corsair','dreadnought','chest','colony','shipyard','repair','rock-a','rock-b','kelp','coral','fan','wreck','vent',...['torpedo','arc','flak','mortar','mines','harpoon','drone','cryo','sonar','salvage','repair','armor'].map(k=>'module-'+k),...Object.keys(window.UBContent.ARTIFACTS).map(k=>'relic-'+k),...(window.UBWorld?.WORLD_ASSETS||[]),...(window.UBWorld?.EXPANSION_ASSETS||[])];let done=0;await Promise.all(names.map(async name=>{const g=await loader.loadAsync('./assets/models/'+name+'.glb');g.scene.traverse(o=>{if(o.isMesh){o.userData.sharedAsset=true;o.castShadow=false;o.receiveShadow=true;if(o.material){o.material.envMapIntensity=.9;}}});this.assets[name]=g.scene;this.assetSizes[name]=new THREE.Box3().setFromObject(g.scene).getSize(new THREE.Vector3());this.onLoad(false,null,++done/names.length);}));}
 clone(name,shadow=false){const original=this.assets[name];if(!original)return new THREE.Group();const o=original.clone(true);o.userData.assetName=name;o.traverse(c=>{if(c.isMesh)c.castShadow=shadow;});return o;}
 setupEnvironment(){this.worldView.setRegion(0,1927,[],true);}
 repositionDeco(x,z){this.plankton.position.set(x,0,z);}
 // Only dispose runtime-owned resources; world GLBs and instance geometry are shared.
 release(group){if(!group)return;this.scene.remove(group);const geometries=new Set(),materials=new Set();group.traverse(o=>{for(const m of o.userData.ownedLivery||[])materials.add(m);for(const m of o.userData.ownedGuardian||[])materials.add(m);if(o.userData.sharedAsset)return;if(o.geometry&&!o.isSprite)geometries.add(o.geometry);if(o.material)for(const m of Array.isArray(o.material)?o.material:[o.material])materials.add(m);});for(const g of geometries)g.dispose();for(const m of materials){if(m.userData?.ownedTexture)m.map?.dispose();m.dispose();}}
 cardPortrait(name){return this.thumbnail(name,420);}
 thumbnail(name,resolution=240){
  const cacheKey=resolution===240?name:name+'@'+resolution;if(this.thumbnails.has(cacheKey))return this.thumbnails.get(cacheKey);if(!this.assets[name])return '';
  const sc=new THREE.Scene();sc.environment=this.environment;sc.add(new THREE.HemisphereLight(0xcce9df,0x102833,2.5));const sun=new THREE.DirectionalLight(0xffdfb0,4);sun.position.set(-3,7,5);sc.add(sun);
  const o=this.clone(name),box=new THREE.Box3().setFromObject(o),center=box.getCenter(new THREE.Vector3()),size=box.getSize(new THREE.Vector3()),reach=Math.max(size.x,size.y,size.z,1);o.position.sub(center);sc.add(o);o.updateMatrixWorld(true);box.setFromObject(o);
  const cam=new THREE.OrthographicCamera(-1,1,1,-1,.05,reach*8+20);cam.position.set(4,3.2,6).normalize().multiplyScalar(reach*2.5+5);cam.lookAt(0,0,0);cam.updateMatrixWorld(true);
  let minX=Infinity,maxX=-Infinity,minY=Infinity,maxY=-Infinity;for(const x of [box.min.x,box.max.x])for(const y of [box.min.y,box.max.y])for(const z of [box.min.z,box.max.z]){const p=new THREE.Vector3(x,y,z).applyMatrix4(cam.matrixWorldInverse);minX=Math.min(minX,p.x);maxX=Math.max(maxX,p.x);minY=Math.min(minY,p.y);maxY=Math.max(maxY,p.y);}const span=Math.max(maxX-minX,maxY-minY)*1.14;cam.left=-span*.5;cam.right=span*.5;cam.top=span*.5;cam.bottom=-span*.5;cam.updateProjectionMatrix();
  const target=new THREE.WebGLRenderTarget(resolution,resolution);target.texture.colorSpace=THREE.SRGBColorSpace;const old=this.renderer.getRenderTarget(),color=this.renderer.getClearColor(new THREE.Color()),alpha=this.renderer.getClearAlpha(),pixels=new Uint8Array(resolution*resolution*4);
  try{this.renderer.setClearColor(0x000000,0);this.renderer.setRenderTarget(target);this.renderer.render(sc,cam);this.renderer.readRenderTargetPixels(target,0,0,resolution,resolution,pixels);}finally{this.renderer.setRenderTarget(old);this.renderer.setClearColor(color,alpha);target.dispose();sc.remove(o);}
  const canvas=document.createElement('canvas');canvas.width=canvas.height=resolution;const ctx=canvas.getContext('2d'),data=ctx.createImageData(resolution,resolution),stride=resolution*4;for(let y=0;y<resolution;y++)data.data.set(pixels.subarray((resolution-1-y)*stride,(resolution-y)*stride),y*stride);ctx.putImageData(data,0,0);const url=canvas.toDataURL();this.thumbnails.set(cacheKey,url);return url;
 }
 setMenuHull(hull,appearance=this.menuAppearance){this.menuHull=hull;this.menuAppearance=appearance;if(this.loading)return;if(this.menuModel)this.release(this.menuModel);const group=this.createShip(hull,['torpedo','arc','flak','salvage','mortar'],3,true,appearance);group.scale.setScalar(3.15);group.position.set(17,6,0);group.rotation.y=.5;this.menuModel=group;this.scene.add(group);}
 createShip(hull,modules=[],tier=1,shadow=false,appearance=null,options={}){
  const g=new THREE.Group();g.add(this.clone(hull,shadow));
  const lampMat=new THREE.SpriteMaterial({map:this.lightTexture,color:0xa0ffdb,transparent:true,opacity:.48,blending:THREE.AdditiveBlending,depthWrite:false});for(const z of [-.75,.75]){const lamp=new THREE.Sprite(lampMat);lamp.position.set(4.65,1.75,z);lamp.scale.set(2.2,2.2,1);g.add(lamp);}
  const engineMat=new THREE.SpriteMaterial({map:this.lightTexture,color:0x75e9db,transparent:true,opacity:.25,blending:THREE.AdditiveBlending,depthWrite:false});for(const z of [-.85,.85]){const lamp=new THREE.Sprite(engineMat);lamp.position.set(-4.6,1.3,z);lamp.userData.engineGlow=true;lamp.scale.setScalar(1.3);g.add(lamp);}
  const beamGeo=new THREE.ConeGeometry(3.2,20,20,1,true);beamGeo.translate(0,-10,0);beamGeo.rotateZ(Math.PI/2);const beam=new THREE.Mesh(beamGeo,new THREE.MeshBasicMaterial({color:0x9affd3,transparent:true,opacity:.022,side:THREE.DoubleSide,depthWrite:false,blending:THREE.AdditiveBlending}));beam.position.set(4.3,1.6,0);g.add(beam);
  const root=new THREE.Group(),baseScale=window.UBContent?.HULLS[hull]?.visualScale||1;g.scale.setScalar(baseScale);g.userData.shipBody=true;root.add(g);root.userData.hull=hull;root.userData.baseScale=baseScale;root.userData.baseRadius=window.UBContent?.HULLS[hull]?.radius||30;applyLivery(g,appearance);root.userData.appearance=g.userData.appearance;
  root.shipAssembly=new ShipAssembly(this,root,g,hull,shadow,appearance);root.shipAssembly.sync(tier,modules,options.states||null,false,options.showcase??tier>1);return root;
 }
 setGraphics(options={}){this.graphicsOptions={quality:['low','balanced','cinematic'].includes(options.quality)?options.quality:'balanced',distortion:options.distortion!==false};this.post.configure({...this.graphicsOptions,reducedMotion:this.reducedMotion});return this.graphics;}
 get graphics(){return{...this.graphicsOptions,effectiveQuality:this.post?.enabled?this.graphicsOptions.quality:'low',hdr:!!this.post?.hdr,reducedMotion:this.reducedMotion};}
 guardianCue(e){this.impactFX.guardianCue?.(e);if(e.type==='guardianSinking')this.post.pulse({x:e.x,y:e.y,r:170,strength:.35,life:.85,kind:'collapse'});this.onGuardianCue?.(e);}
 setGame(game){this.post.clear();this.post.update(0,{stage:game?.stage||0,mode:game?'ocean':'menu',reducedMotion:this.reducedMotion});this.guardianFX.clear();this.combatFX.clear();this.impactFX.clear();this.shake=0;this.game=game;this.resize();if(this.menuModel)this.menuModel.visible=!game;for(const map of [this.entities,this.props,this.bullets]){for(const o of map.values())this.release(o);map.clear();}if(this.shield)this.shield.visible=false;this.shipSignature='';this.stage=-1;this.focus.set(game?.p.x*S||0,0,game?.p.y*S||0);this.gold.count=0;for(const f of this.fx)this.release(f.obj);this.fx=[];for(const t of this.damageTexts)t.el.remove();this.damageTexts=[];}
 resize(){const w=innerWidth,h=innerHeight;this.renderer.setSize(w,h);const height=(this.game?(w<650?80:68):56)*this.zoom;this.camera.left=-height*w/h/2;this.camera.right=height*w/h/2;this.camera.top=height/2;this.camera.bottom=-height/2;this.camera.updateProjectionMatrix();this.post?.resize();}
 setZoom(delta){this.zoom=THREE.MathUtils.clamp(this.zoom+delta,.7,1.4);this.resize();}
 setStage(index){this.stage=index;const b=OCEAN_PALETTES[index];this.scene.background.setHex(b.water);this.scene.fog.color.setHex(b.water);this.scene.fog.density=[.0042,.0045,.0052][index];this.fill.color.setHex(index===2?0x8097ed:index===1?0x80aebf:0x7bcbb0);this.hemi.intensity=[1.65,1.5,1.35][index];this.sun.intensity=[3.6,3.1,2.65][index];this.sun.color.setHex(index===2?0xbcd6fb:index===1?0xefd6b1:0xffe6b8);this.post.combine.uniforms.glow.value=[.2,.22,.28][index];}
 addSprite(x,y,size,color,life=.5,vy=0){if(this.fx.length>350)return;const m=new THREE.SpriteMaterial({map:this.lightTexture,color,transparent:true,opacity:.8,blending:THREE.AdditiveBlending,depthWrite:false});const o=new THREE.Sprite(m);o.position.set(x*S,4,y*S);o.scale.setScalar(size);this.scene.add(o);this.fx.push({obj:o,life,max:life,size,vy,type:'sprite'});}
 ring(x,y,r,color,life=.8){const geo=new THREE.RingGeometry(.94,1,96);geo.rotateX(-Math.PI/2);const o=new THREE.Mesh(geo,new THREE.MeshBasicMaterial({color,transparent:true,opacity:.9,side:THREE.DoubleSide,depthWrite:false,blending:THREE.AdditiveBlending}));o.position.set(x*S,4,y*S);this.scene.add(o);this.fx.push({obj:o,life,max:life,size:r*S,type:'ring'});}
 lightning(e){const pts=[];for(let i=0;i<10;i++){const t=i/9;pts.push(new THREE.Vector3((e.x+(e.tx-e.x)*t)*S+(i&&i<9?(Math.random()-.5)*1.5:0),4+Math.sin(t*Math.PI)*1.2,(e.y+(e.ty-e.y)*t)*S+(i&&i<9?(Math.random()-.5)*1.5:0)));}const geo=new THREE.BufferGeometry().setFromPoints(pts);const o=new THREE.Line(geo,new THREE.LineBasicMaterial({color:0xbbffe0,transparent:true,opacity:1,blending:THREE.AdditiveBlending}));this.scene.add(o);this.fx.push({obj:o,life:.16,max:.16,type:'line'});this.addSprite(e.tx,e.ty,3,palette.mint,.2);}
 label(e,text,color,large=false){if(this.damageTexts.length>35)return;const el=document.createElement('span');el.className='world-number'+(large?' big':'');el.textContent=text;el.style.color=color;document.getElementById('world-labels')?.append(el);this.damageTexts.push({el,x:e.x*S,z:e.y*S,age:0,life:large?1.6:.85});}
 event(e){this.guardianFX.event(e);this.combatFX.event(e);this.impactFX.event(e,this.game);
  if(e.type==='sonar')this.post.pulse({x:e.x,y:e.y,r:e.r,strength:.65,life:1.1,kind:'sonar'});
  if(e.type==='explode'&&(e.boss||e.elite))this.post.pulse({x:e.x,y:e.y,r:e.size*2.4,strength:e.boss?.85:.42,life:e.boss?1.15:.7,kind:'blast'});
  if(e.type==='ram')this.post.pulse({x:e.x,y:e.y,r:100,strength:.24,life:.45,kind:'ram'});
  if(e.type==='shot'){const ship=this.entities.get('player'),point=ship?.shipAssembly?.shot(e.key,e.active,e.a,e.side);this.impactFX.muzzle(point,e.key,e.active);if(e.active&&!this.reducedMotion)this.shake=Math.max(this.shake,.12);}
  if(e.type==='bossStrike'&&e.pattern==='fan'){const ship=this.entities.get(e.id),point=ship?.shipAssembly?.shot('flak',true,e.a);this.impactFX.muzzle(point,'flak',true);}
  if(e.type==='ram'&&!this.reducedMotion)this.shake=Math.min(.8,.28+(e.impulse||0)*.0015);
  if(e.type==='gold'){if(e.value>=8)this.label(e,'+'+e.value+' G','#f1ce83',true);if(Math.random()<.35)this.addSprite(e.x,e.y,1.7,palette.gold,.3,1);}
  if(e.type==='damage'){if(e.crit||e.value>=25)this.label(e,(e.crit?'✦ ':'')+e.value,e.crit?'#ffe4a7':'#dee9db',e.crit);}
  if(e.type==='consume'){this.addSprite(e.x,e.y,8,palette.gold,.6,1);this.ring(e.x,e.y,70,palette.gold,.5);}
  if(e.type==='explode'&&!this.reducedMotion)this.shake=Math.max(this.shake,e.boss?.7:e.elite?.35:.12);
  if(e.type==='blast'){this.addSprite(e.x,e.y,e.r*.15,e.family==='cryo'?palette.ice:palette.gold,.4);this.ring(e.x,e.y,e.r,e.family==='electric'?palette.mint:palette.gold,.6);}
  if(e.type==='sonar'){this.ring(e.x,e.y,e.r,palette.mint,1.1);this.ring(e.x,e.y,e.r*.7,palette.mint,.8);this.shake=.32;}
  if(e.type==='arc')this.lightning(e);
  if(e.type==='frost'){this.ring(e.x,e.y,e.r,palette.ice,e.active?.9:.35);if(e.active)this.addSprite(e.x,e.y,28,palette.ice,.7);}
  if(e.type==='heal'){this.label(e,'+'+e.value+' HULL','#9de8bd',true);this.ring(e.x,e.y,95,palette.mint,.6);}
  if(e.type==='chest'){this.addSprite(e.x,e.y,15,palette.gold,1.5,2);this.ring(e.x,e.y,150,palette.gold,1.2);}
  if(e.type==='level'||e.type==='artifact'||e.type==='evolution'){if(this.game)this.ring(this.game.p.x,this.game.p.y,180,e.type==='level'?palette.mint:palette.violet,1);}
  if(e.type==='mineralFire'){this.ring(e.x,e.y,e.r,0xff9248,4);this.addSprite(e.x,e.y,16,0xfa7842,4,.3);}
  if(e.type==='bossCharge'){this.ring(e.x,e.y,220,palette.red,.9);this.addSprite(e.x,e.y,12,palette.red,.6);}
  if(e.type==='hit')this.shake=.6;
 }
 syncShip(game,dt=0){const signature=game.hull+'|'+appearanceKey(game.harborLoadout);let o=this.entities.get('player');if(signature!==this.shipSignature||!o){if(o)this.release(o);o=this.createShip(game.hull,game.moduleOrder,game.tier,true,game.harborLoadout,{states:game.modules,showcase:false});this.entities.set('player',o);this.scene.add(o);this.shipSignature=signature;}else o.shipAssembly.sync(game.tier,game.moduleOrder,game.modules,true,false);
  const p=game.p;o.position.set(p.x*S,2.1+(this.reducedMotion?0:Math.sin(this.clock*1.5)*.09),p.y*S);o.rotation.y=-p.a;o.rotation.z=0;o.scale.setScalar(p.r/(window.UBContent.HULLS[game.hull]?.radius||30));o.shipAssembly.update(dt,p);
  if(p.shield>0||p.hit>0){if(!this.shield){this.shield=new THREE.Mesh(new THREE.SphereGeometry(7,24,16),new THREE.MeshBasicMaterial({color:0x94fce1,wireframe:true,transparent:true,opacity:.08,depthWrite:false}));this.scene.add(this.shield);}this.shield.visible=true;this.shield.position.copy(o.position);this.shield.position.y+=2;this.shield.scale.set((p.r*S+2.5)/7,(p.r*S+1.6)/7,(p.r*S+2.5)/7);}else if(this.shield)this.shield.visible=false;
 }
 syncEnemies(game,dt=0){
  const ids=new Set(['player']),special=['minelayer','sniper','carrier','leech','warden','artillery','tender','kamikaze'];
  for(const e of game.enemies){if(e.hp<=0)continue;ids.add(e.id);let o=this.entities.get(e.id);
   if(!o){let model;
    if(e.kind==='shoal'){o=new THREE.Mesh(new THREE.CapsuleGeometry(.27,.55,2,5),new THREE.MeshStandardMaterial({color:0xe6b56a,metalness:.3,roughness:.35,emissive:0x402706}));o.geometry.rotateZ(Math.PI/2);model='shoal';}
    else if(special.includes(e.kind)){model='enemy-'+e.kind;o=this.clone(model);}
    else if(e.kind==='boss'){
     const role=e.bossRole||['vanguard','hunter','sovereign'][e.bossWave]||'sovereign';model={vanguard:'enemy-bellwarden',hunter:'enemy-jagddom',sovereign:'enemy-kaiserburg'}[role]||'enemy-kaiserburg';
     const index=['vanguard','hunter','sovereign'].indexOf(role),mods=role==='vanguard'?['flak','armor','mortar']:role==='hunter'?['rail','harpoon','sonic']:['torpedo','flak','mortar','arc'];
     o=this.createShip(model,mods,1,false,{paint:{id:'guardian-'+role,hull:[0x315963,0x383058,0x652e38][index],accent:[0xd7b779,0xbcb0e0,0xe7be67][index],light:[0xffd69a,0xc5d6ff,0xff9c7d][index]}});o.userData.bossRole=role;
    }else{model=({scout:'wraith',rammer:'wraith',gunner:'nautilus',fort:'bastion',elite:'enemy-bellwarden'})[e.kind]||'corsair';const mods=e.kind==='elite'?['torpedo','flak','mortar']:e.kind==='fort'?['torpedo','flak']:e.kind==='gunner'?['flak']:e.kind==='rammer'?['harpoon']:['torpedo'];o=this.createShip(model,mods,1,false,{paint:{id:'hostile-'+e.kind,hull:e.kind==='elite'?0x554357:0x683f44,accent:0xb89872,light:0xff9c84}});}
    o.userData.enemyKind=e.kind;o.userData.renderModel=model;o.userData.planarSize=Math.max(this.assetSizes[model]?.x||1,this.assetSizes[model]?.z||1)*(o.userData.baseScale||1);this.scene.add(o);this.entities.set(e.id,o);
   }
   const scale=e.kind==='shoal'?1:Math.max(8,e.r)*S*2/o.userData.planarSize;o.scale.setScalar(scale);o.userData.collisionRadius=e.r;o.position.set(e.x*S,e.kind==='shoal'?1.6:2+Math.sin(this.clock+e.id)*.08,e.y*S);o.rotation.y=-e.a;o.visible=Math.hypot(e.x-game.p.x,e.y-game.p.y)<1450;if(o.visible)o.shipAssembly?.update(dt);
  }
  for(const[id,o]of this.entities)if(!ids.has(id)){this.guardianFX.forget(id);this.release(o);this.entities.delete(id);}
 }
 syncProps(game){const ids=new Set();for(const p of game.props){ids.add(p.id);let o=this.props.get(p.id);if(!o){const model=({habitat:'colony',cache:'chest',wreck:'wreck',repair:'repair',shipyard:'shipyard',chest:'chest'})[p.kind];o=new THREE.Group();const body=this.clone(model);o.add(body);o.userData.body=body;if(p.kind==='chest'||p.kind==='repair'||p.kind==='shipyard'){const color=p.kind==='chest'?palette.gold:p.kind==='repair'?palette.mint:palette.ice;const m=new THREE.SpriteMaterial({map:this.lightTexture,color,transparent:true,opacity:.65,depthWrite:false,blending:THREE.AdditiveBlending});const s=new THREE.Sprite(m);s.position.y=p.kind==='chest'?2.8:5;s.scale.set(3,7,1);o.add(s);o.userData.beacon=s;const ring=new THREE.Mesh(new THREE.RingGeometry(3.9,4.1,48).rotateX(-Math.PI/2),new THREE.MeshBasicMaterial({color,transparent:true,opacity:.3,depthWrite:false,side:THREE.DoubleSide}));ring.position.y=.15;o.add(ring);o.userData.ring=ring;}this.props.set(p.id,o);this.scene.add(o);}const y=seabedHeight(p.x*S,p.y*S,game.stage);o.position.set(p.x*S,y+.1,p.y*S);o.rotation.y=p.a;const scale=p.kind==='habitat'?1+p.tier*.25:p.kind==='chest'?1.35:p.kind==='wreck'?1.1:1;o.scale.setScalar(scale);o.visible=!p.used&&Math.hypot(p.x-game.p.x,p.y-game.p.y)<1450;if(o.userData.beacon)o.userData.beacon.material.opacity=.45+Math.sin(this.clock*2+p.id)*.2;}
  for(const [id,o]of this.props)if(!ids.has(id)){this.release(o);this.props.delete(id);}
 }
 syncProjectiles(game){const ids=new Set();for(const b of [...game.projectiles,...game.mines.map(m=>({...m,key:'mine'}))]){ids.add(b.id);let o=this.bullets.get(b.id);if(!o){const color=b.enemy?palette.red:b.key==='rail'?palette.ice:b.key==='sonic'?0xc2faff:b.key==='flame'?0xff9954:b.key==='mine'?palette.gold:b.key==='harpoon'?0xddd9b6:b.key==='drone'?palette.mint:palette.gold;const geo=b.key==='mine'?new THREE.IcosahedronGeometry(.45,0):new THREE.CapsuleGeometry(b.enemy?.22:.14,b.key==='harpoon'?1.5:.6,2,5).rotateZ(-Math.PI/2);o=new THREE.Mesh(geo,new THREE.MeshStandardMaterial({color,emissive:color,emissiveIntensity:1.6,metalness:.5,roughness:.3}));this.bullets.set(b.id,o);this.scene.add(o);}o.position.set(b.x*S,3.6+(b.height||0)*S,b.y*S);o.rotation.y=-(b.a||0);if(b.key==='mine'){o.position.y=2;o.rotation.y=this.clock*.3;}if(b.key==='torpedo'&&Math.random()<.16)this.impactFX.emit('flash',b.x*S,3.6,b.y*S,.35,.22,palette.mint);}
  for(const [id,o]of this.bullets)if(!ids.has(id)){this.scene.remove(o);o.geometry.dispose();o.material.dispose();this.bullets.delete(id);}
 }
 syncGold(game){this.gold.count=Math.min(750,game.loot.length);for(let i=0;i<this.gold.count;i++){const l=game.loot[i];this.dummy.position.set(l.x*S,2.2+Math.sin(this.clock*3+l.id)*.3,l.y*S);this.dummy.rotation.set(this.clock+l.id,this.clock*2,0);this.dummy.scale.setScalar(l.value>5?1.5:1);this.dummy.updateMatrix();this.gold.setMatrixAt(i,this.dummy.matrix);}this.gold.instanceMatrix.needsUpdate=true;}
 project(x,y,height=3){const v=new THREE.Vector3(x*S,height,y*S).project(this.camera);return {x:(v.x*.5+.5)*innerWidth,y:(-.5*v.y+.5)*innerHeight};}
 update(dt,game){this.clock+=dt;if(this.loading){this.renderer.render(this.scene,this.camera);return;}this.shake*=Math.exp(-dt*9);const t=this.clock,effectDt=game?.state==='paused'?0:dt;
  if(game){if(this.stage!==game.stage)this.setStage(game.stage);this.worldView.setRegion(game.stage,game.worldSeed||1927,game.world?.landmarks||[]);this.focus.lerp(new THREE.Vector3(game.p.x*S,0,game.p.y*S),1-Math.exp(-dt*5));this.syncShip(game,dt);this.syncEnemies(game,dt);this.syncProps(game);this.syncProjectiles(game);this.syncGold(game);this.combatFX.update(dt,game);this.guardianFX.update(effectDt,game);if(this.menuModel)this.menuModel.visible=false;}
  else {this.worldView.setRegion(0,1927,[],true);if(this.menuModel){this.menuModel.visible=true;this.menuModel.shipAssembly?.update(dt);this.menuModel.rotation.y=.48+Math.sin(t*.13)*.12;this.menuModel.position.y=(this.harborPreview&&innerWidth<720?(innerHeight<720?8.5:13):6)+Math.sin(t*.8)*.13;this.menuModel.position.x=this.harborPreview&&innerWidth<720?0:17;this.menuModel.scale.setScalar(this.harborPreview&&innerWidth<720?(innerHeight<720?1.05:1.65):3.15);}this.focus.lerp(new THREE.Vector3(0,0,0),1-Math.exp(-dt*4));if(this.stage!==0)this.setStage(0);}
  this.repositionDeco(this.focus.x,this.focus.z);this.worldView.update(dt,this.focus,this.camera,game);this.plankton.rotation.y=Math.sin(t*.05)*.025;
  for(let i=0;i<100;i++){const flock=Math.floor(i/10),j=i%10,x=this.focus.x+(hash(flock+700)-.5)*150+Math.sin(t*.06+flock)*20,z=this.focus.z+(hash(flock+800)-.5)*110;this.dummy.position.set(x+j*.9,4+hash(flock)*10+Math.sin(t*.9+i)*.2,z+Math.sin(j*2.4)*1.8);this.dummy.rotation.set(0,Math.sin(t*.06+flock)*.15,0);this.dummy.scale.setScalar(.5+hash(flock)*.5);this.dummy.updateMatrix();this.fish.setMatrixAt(i,this.dummy.matrix);}this.fish.instanceMatrix.needsUpdate=true;
  for(let i=this.fx.length-1;i>=0;i--){const f=this.fx[i];f.life-=dt;if(f.life<=0){this.release(f.obj);this.fx.splice(i,1);continue;}const a=1-f.life/f.max;f.obj.material.opacity=(1-a)*(f.type==='sprite'?.8:.75);if(f.type==='ring')f.obj.scale.setScalar(Math.max(.01,f.size*a));if(f.type==='sprite'){f.obj.scale.setScalar(f.size*(1+a*.7));f.obj.position.y+=(f.vy||0)*dt;}}
  const offset=game?new THREE.Vector3(0,90,76):new THREE.Vector3(0,75,74);this.camera.position.copy(this.focus).add(offset);if(!this.reducedMotion){this.camera.position.x+=Math.sin(t*49)*Math.min(.8,this.shake)*.5;this.camera.position.z+=Math.cos(t*43)*Math.min(.8,this.shake)*.35;}this.camera.lookAt(this.focus);this.sun.position.copy(this.focus).add(new THREE.Vector3(-40,85,15));this.sun.target.position.copy(this.focus);this.sun.target.updateMatrixWorld();
  for(let i=this.damageTexts.length-1;i>=0;i--){const d=this.damageTexts[i];d.age+=dt;if(d.age>d.life){d.el.remove();this.damageTexts.splice(i,1);continue;}const p=this.project(d.x/S,d.z/S,7+d.age*3);d.el.style.transform=`translate(${p.x}px,${p.y}px)`;d.el.style.opacity=String(Math.min(1,(d.life-d.age)*3));}
  this.impactFX.update(effectDt,this.camera);this.post.update(effectDt,{stage:game?game.stage:0,mode:game?'ocean':'menu',reducedMotion:this.reducedMotion});this.post.render(this.scene,this.camera);
 }
 get stats(){return {graphics:this.graphics,post:this.post.state,guardians:this.guardianFX.stats,growth:(this.entities.get('player')||this.menuModel)?.shipAssembly?.stats,impacts:this.impactFX.stats,reducedMotion:this.reducedMotion,bloom:this.post?.enabled,antialiasSamples:this.post?.target.samples||0,calls:this.post?.stats?.calls??this.renderer.info.render.calls,triangles:this.post?.stats?.triangles??this.renderer.info.render.triangles,world:this.worldView?.stats,geometries:this.renderer.info.memory.geometries,textures:this.renderer.info.memory.textures,assets:Object.keys(this.assets).length,combatTelegraphs:this.combatFX.objects.size,appearance:this.entities.get('player')?.userData.appearance||this.menuModel?.userData.appearance||'original/none',fleet:{hull:this.game?.hull||this.menuHull,baseScale:(this.entities.get('player')||this.menuModel)?.userData.baseScale||1,radius:this.game?.p.r||null,enemies:Object.fromEntries([...this.entities.values()].filter(o=>o.userData.renderModel).reduce((a,o)=>a.set(o.userData.renderModel,(a.get(o.userData.renderModel)||0)+1),new Map()))},telegraphKinds:this.combatFX.stats};}
}
