import * as THREE from './assets/lib/three.module.js';
import {GLTFLoader} from './assets/lib/GLTFLoader.js';
import {OceanWorld,OCEAN_PALETTES} from './ocean-world.js';
import {OceanPost} from './ocean-post.js';
const S=.1,TAU=Math.PI*2,hash=n=>{const x=Math.sin(n*127.1+311.7)*43758.5453;return x-Math.floor(x);};
const palette={gold:0xffc86f,mint:0x91ffda,red:0xff876b,ice:0x9feaff,violet:0xbf9fff};
function radialTexture(){const c=document.createElement('canvas');c.width=c.height=64;const x=c.getContext('2d'),g=x.createRadialGradient(32,32,0,32,32,32);g.addColorStop(0,'rgba(255,255,255,1)');g.addColorStop(.15,'rgba(255,255,255,.8)');g.addColorStop(.45,'rgba(255,255,255,.2)');g.addColorStop(1,'rgba(255,255,255,0)');x.fillStyle=g;x.fillRect(0,0,64,64);return new THREE.CanvasTexture(c);}
function seabedHeight(x,z,stage=0){return window.UBWorld?.heightAt(x,z,stage)??-1;}
export class OceanView{
 constructor(canvas,onLoad=()=>{}){
  this.canvas=canvas;this.renderer=new THREE.WebGLRenderer({canvas,antialias:true,alpha:false,powerPreference:'high-performance'});this.renderer.setPixelRatio(Math.min(devicePixelRatio||1,1.5));this.renderer.setSize(innerWidth,innerHeight);this.renderer.outputColorSpace=THREE.SRGBColorSpace;this.renderer.toneMapping=THREE.ACESFilmicToneMapping;this.renderer.toneMappingExposure=1.18;this.renderer.shadowMap.enabled=true;this.renderer.shadowMap.type=THREE.PCFSoftShadowMap;
  this.scene=new THREE.Scene();this.scene.background=new THREE.Color(0x133c4a);this.scene.fog=new THREE.FogExp2(0x153e4a,.0038);this.camera=new THREE.OrthographicCamera(-60,60,40,-40,.1,650);this.camera.position.set(0,100,95);this.target=new THREE.Vector3();this.camera.lookAt(this.target);this.clock=0;this.assets={};this.entities=new Map();this.props=new Map();this.bullets=new Map();this.fx=[];this.damageTexts=[];this.shake=0;this.stage=-1;this.focus=new THREE.Vector3();this.loading=true;this.onLoad=onLoad;this.thumbnails=new Map();this.menuHull='nautilus';this.menuModel=null;this.shipSignature='';this.game=null;this.ambient=[];this.zoom=1;this.lastDeco={x:Infinity,z:Infinity};
  this.lightTexture=radialTexture();this.setupLighting();this.setupSea();this.setupResources();this.setupAtmosphere();this.post=new OceanPost(this.renderer);this.resize();addEventListener('resize',()=>this.resize());
  this.ready=this.loadAssets().then(()=>{this.loading=false;this.setupEnvironment();this.setMenuHull('nautilus');onLoad(true);}).catch(e=>{console.error(e);this.error=e;onLoad(false,e);});
 }
 setupLighting(){
  this.hemi=new THREE.HemisphereLight(0xb4ecd6,0x092232,1.65);this.scene.add(this.hemi);this.sun=new THREE.DirectionalLight(0xffe1af,3.6);this.sun.position.set(-40,85,15);this.sun.castShadow=true;this.sun.shadow.mapSize.set(2048,2048);Object.assign(this.sun.shadow.camera,{left:-70,right:70,top:70,bottom:-70,near:1,far:220});this.sun.shadow.bias=-.001;this.sun.shadow.normalBias=.12;this.scene.add(this.sun);this.scene.add(this.sun.target);
  const fill=new THREE.DirectionalLight(0x5bbabf,1.05);fill.position.set(25,20,-40);this.scene.add(fill);this.fill=fill;
  const faces=[];for(let i=0;i<6;i++){const c=document.createElement('canvas');c.width=c.height=32;const x=c.getContext('2d'),g=x.createLinearGradient(0,0,0,32);g.addColorStop(0,i===2?'#c3dac2':'#456b6e');g.addColorStop(.5,'#365454');g.addColorStop(1,'#152d38');x.fillStyle=g;x.fillRect(0,0,32,32);faces.push(c);}this.environment=new THREE.CubeTexture(faces);this.environment.needsUpdate=true;this.environment.colorSpace=THREE.SRGBColorSpace;this.scene.environment=this.environment;
 }
 setupSea(){this.worldView=new OceanWorld(this);this.floor=this.worldView.floor;this.caustics=this.worldView.caustic;}
 setupResources(){const goldGeo=new THREE.IcosahedronGeometry(.32,0);this.gold=new THREE.InstancedMesh(goldGeo,new THREE.MeshStandardMaterial({color:0xffcf74,metalness:.65,roughness:.23,emissive:0x986220,emissiveIntensity:.6}),760);this.gold.instanceMatrix.setUsage(THREE.DynamicDrawUsage);this.gold.count=0;this.gold.frustumCulled=false;this.scene.add(this.gold);this.dummy=new THREE.Object3D();
  const bubbleGeo=new THREE.BufferGeometry(),pos=new Float32Array(750*3);for(let i=0;i<750;i++){pos[i*3]=(hash(i*7)-.5)*240;pos[i*3+1]=hash(i*19)*45;pos[i*3+2]=(hash(i*11)-.5)*180;}bubbleGeo.setAttribute('position',new THREE.BufferAttribute(pos,3));this.plankton=new THREE.Points(bubbleGeo,new THREE.PointsMaterial({map:this.lightTexture,color:0xa8e4d5,size:.15,transparent:true,opacity:.35,depthWrite:false,blending:THREE.AdditiveBlending}));this.scene.add(this.plankton);
 }
 setupAtmosphere(){const fishGeo=new THREE.ConeGeometry(.23,1.1,4);fishGeo.rotateZ(-Math.PI/2);this.fish=new THREE.InstancedMesh(fishGeo,new THREE.MeshStandardMaterial({color:0x9eccc0,metalness:.3,roughness:.5}),100);this.fish.instanceMatrix.setUsage(THREE.DynamicDrawUsage);this.fish.frustumCulled=false;this.scene.add(this.fish);}
 async loadAssets(){const loader=new GLTFLoader();const names=['nautilus','bastion','wraith','corsair','dreadnought','chest','colony','shipyard','repair','rock-a','rock-b','kelp','coral','fan','wreck','vent',...['torpedo','arc','flak','mortar','mines','harpoon','drone','cryo','sonar','salvage','repair','armor'].map(k=>'module-'+k),...Object.keys(window.UBContent.ARTIFACTS).map(k=>'relic-'+k),...(window.UBWorld?.WORLD_ASSETS||[])];let done=0;await Promise.all(names.map(async name=>{const g=await loader.loadAsync('./assets/models/'+name+'.glb');g.scene.traverse(o=>{if(o.isMesh){o.userData.sharedAsset=true;o.castShadow=false;o.receiveShadow=true;if(o.material){o.material.envMapIntensity=.9;}}});this.assets[name]=g.scene;this.onLoad(false,null,++done/names.length);}));}
 clone(name,shadow=false){const original=this.assets[name];if(!original)return new THREE.Group();const o=original.clone(true);o.traverse(c=>{if(c.isMesh)c.castShadow=shadow;});return o;}
 setupEnvironment(){this.worldView.setRegion(0,1927,[],true);}
 repositionDeco(x,z){this.plankton.position.set(x,0,z);}
 // Only dispose runtime-owned resources; world GLBs and instance geometry are shared.
 release(group){if(!group)return;this.scene.remove(group);const geometries=new Set(),materials=new Set();group.traverse(o=>{if(o.userData.sharedAsset)return;if(o.geometry&&!o.isSprite)geometries.add(o.geometry);if(o.material)for(const m of Array.isArray(o.material)?o.material:[o.material])materials.add(m);});for(const g of geometries)g.dispose();for(const m of materials)m.dispose();}
 thumbnail(name){if(this.thumbnails.has(name))return this.thumbnails.get(name);if(!this.assets[name])return '';const sc=new THREE.Scene();sc.environment=this.environment;sc.add(new THREE.HemisphereLight(0xcce9df,0x102833,2.5));const sun=new THREE.DirectionalLight(0xffdfb0,4);sun.position.set(-3,7,5);sc.add(sun);const o=this.clone(name),box=new THREE.Box3().setFromObject(o),center=box.getCenter(new THREE.Vector3()),size=box.getSize(new THREE.Vector3()),span=Math.max(size.x,size.y,size.z)*1.38;o.position.sub(center);sc.add(o);const cam=new THREE.OrthographicCamera(-span*.5,span*.5,span*.5,-span*.5,.01,100);cam.position.set(4,3.2,6);cam.lookAt(0,0,0);const target=new THREE.WebGLRenderTarget(240,240);target.texture.colorSpace=THREE.SRGBColorSpace;const old=this.renderer.getRenderTarget(),color=this.renderer.getClearColor(new THREE.Color()),alpha=this.renderer.getClearAlpha();this.renderer.setClearColor(0x000000,0);this.renderer.setRenderTarget(target);this.renderer.render(sc,cam);const pixels=new Uint8Array(240*240*4);this.renderer.readRenderTargetPixels(target,0,0,240,240,pixels);this.renderer.setRenderTarget(old);this.renderer.setClearColor(color,alpha);target.dispose();const canvas=document.createElement('canvas');canvas.width=canvas.height=240;const ctx=canvas.getContext('2d'),data=ctx.createImageData(240,240);for(let y=0;y<240;y++)data.data.set(pixels.subarray((239-y)*960,(240-y)*960),y*960);ctx.putImageData(data,0,0);const url=canvas.toDataURL();this.thumbnails.set(name,url);return url;}
 setMenuHull(hull){this.menuHull=hull;if(this.loading)return;if(this.menuModel)this.release(this.menuModel);const group=this.createShip(hull,['torpedo','arc','flak','salvage','mortar'],3,true);group.scale.setScalar(3.15);group.position.set(17,6,0);group.rotation.y=.5;this.menuModel=group;this.scene.add(group);}
 createShip(hull,modules=[],tier=1,shadow=false){
  const g=new THREE.Group();g.add(this.clone(hull,shadow));const mounts=[[1.75,2.78,0],[.1,2.78,-2.05],[.1,2.78,2.05],[-3,2.9,0],[2.3,3.9,0],[-1.1,4.75,0]];
  if(tier>1){const deckMat=new THREE.MeshStandardMaterial({color:0x587872,metalness:.65,roughness:.35});for(const side of [-1,1]){const deck=new THREE.Mesh(new THREE.BoxGeometry(5.4,.27,.8+(tier-1)*.42),deckMat);deck.position.set(0,2.64,side*(1.65+(tier-1)*.15));deck.castShadow=shadow;g.add(deck);const pod=this.clone('module-armor',shadow);pod.position.set(-2.7,2.7,side*1.6);pod.scale.setScalar(.75);g.add(pod);}}
  modules.forEach((key,i)=>{const m=this.clone('module-'+key,shadow);const mount=mounts[i%mounts.length];m.position.set(...mount);m.scale.setScalar(i>=4?.7:.83);if(i===1)m.rotation.y=Math.PI/2;if(i===2)m.rotation.y=-Math.PI/2;if(i===3)m.rotation.y=Math.PI;m.userData.module=key;g.add(m);});
  const lampMat=new THREE.SpriteMaterial({map:this.lightTexture,color:0xa0ffdb,transparent:true,opacity:.48,blending:THREE.AdditiveBlending,depthWrite:false});for(const z of [-.75,.75]){const lamp=new THREE.Sprite(lampMat);lamp.position.set(4.65,1.75,z);lamp.scale.set(2.2,2.2,1);g.add(lamp);}
  const beamGeo=new THREE.ConeGeometry(3.2,20,20,1,true);beamGeo.translate(0,-10,0);beamGeo.rotateZ(Math.PI/2);const beam=new THREE.Mesh(beamGeo,new THREE.MeshBasicMaterial({color:0x9affd3,transparent:true,opacity:.022,side:THREE.DoubleSide,depthWrite:false,blending:THREE.AdditiveBlending}));beam.position.set(4.3,1.6,0);g.add(beam);
  g.userData.hull=hull;return g;
 }
 setGame(game){this.game=game;this.resize();if(this.menuModel)this.menuModel.visible=!game;for(const map of [this.entities,this.props,this.bullets]){for(const o of map.values())this.release(o);map.clear();}if(this.shield)this.shield.visible=false;this.shipSignature='';this.stage=-1;this.focus.set(game?.p.x*S||0,0,game?.p.y*S||0);this.gold.count=0;for(const f of this.fx)this.release(f.obj);this.fx=[];for(const t of this.damageTexts)t.el.remove();this.damageTexts=[];}
 resize(){const w=innerWidth,h=innerHeight;this.renderer.setSize(w,h);const height=(this.game?(w<650?80:68):56)*this.zoom;this.camera.left=-height*w/h/2;this.camera.right=height*w/h/2;this.camera.top=height/2;this.camera.bottom=-height/2;this.camera.updateProjectionMatrix();this.post?.resize();}
 setZoom(delta){this.zoom=THREE.MathUtils.clamp(this.zoom+delta,.7,1.4);this.resize();}
 setStage(index){this.stage=index;const b=OCEAN_PALETTES[index];this.scene.background.setHex(b.water);this.scene.fog.color.setHex(b.water);this.scene.fog.density=[.0042,.0045,.0052][index];this.fill.color.setHex(index===2?0x8097ed:index===1?0x80aebf:0x7bcbb0);this.hemi.intensity=[1.65,1.5,1.35][index];this.sun.intensity=[3.6,3.1,2.65][index];this.sun.color.setHex(index===2?0xbcd6fb:index===1?0xefd6b1:0xffe6b8);this.post.combine.uniforms.glow.value=[.2,.22,.28][index];}
 addSprite(x,y,size,color,life=.5,vy=0){if(this.fx.length>350)return;const m=new THREE.SpriteMaterial({map:this.lightTexture,color,transparent:true,opacity:.8,blending:THREE.AdditiveBlending,depthWrite:false});const o=new THREE.Sprite(m);o.position.set(x*S,4,y*S);o.scale.setScalar(size);this.scene.add(o);this.fx.push({obj:o,life,max:life,size,vy,type:'sprite'});}
 ring(x,y,r,color,life=.8){const geo=new THREE.RingGeometry(.94,1,96);geo.rotateX(-Math.PI/2);const o=new THREE.Mesh(geo,new THREE.MeshBasicMaterial({color,transparent:true,opacity:.9,side:THREE.DoubleSide,depthWrite:false,blending:THREE.AdditiveBlending}));o.position.set(x*S,4,y*S);this.scene.add(o);this.fx.push({obj:o,life,max:life,size:r*S,type:'ring'});}
 lightning(e){const pts=[];for(let i=0;i<10;i++){const t=i/9;pts.push(new THREE.Vector3((e.x+(e.tx-e.x)*t)*S+(i&&i<9?(Math.random()-.5)*1.5:0),4+Math.sin(t*Math.PI)*1.2,(e.y+(e.ty-e.y)*t)*S+(i&&i<9?(Math.random()-.5)*1.5:0)));}const geo=new THREE.BufferGeometry().setFromPoints(pts);const o=new THREE.Line(geo,new THREE.LineBasicMaterial({color:0xbbffe0,transparent:true,opacity:1,blending:THREE.AdditiveBlending}));this.scene.add(o);this.fx.push({obj:o,life:.16,max:.16,type:'line'});this.addSprite(e.tx,e.ty,3,palette.mint,.2);}
 label(e,text,color,large=false){if(this.damageTexts.length>35)return;const el=document.createElement('span');el.className='world-number'+(large?' big':'');el.textContent=text;el.style.color=color;document.getElementById('world-labels')?.append(el);this.damageTexts.push({el,x:e.x*S,z:e.y*S,age:0,life:large?1.6:.85});}
 event(e){
  if(e.type==='gold'){if(e.value>=8)this.label(e,'+'+e.value+' G','#f1ce83',true);if(Math.random()<.35)this.addSprite(e.x,e.y,1.7,palette.gold,.3,1);}
  if(e.type==='damage'){if(e.crit||e.value>=25)this.label(e,(e.crit?'✦ ':'')+e.value,e.crit?'#ffe4a7':'#dee9db',e.crit);}
  if(e.type==='consume'){this.addSprite(e.x,e.y,8,palette.gold,.6,1);this.ring(e.x,e.y,70,palette.gold,.5);}
  if(e.type==='explode'){this.shake=e.boss?1.4:e.elite?.7:.25;this.addSprite(e.x,e.y,e.size*.35,palette.gold,.45);this.addSprite(e.x,e.y,e.size*.55,palette.red,.7,2);this.ring(e.x,e.y,e.size*1.7,palette.gold,.65);for(let i=0;i<(e.boss?24:8);i++){const a=i/8*TAU;this.addSprite(e.x+Math.cos(a)*e.size,e.y+Math.sin(a)*e.size,.8+Math.random()*1.2,palette.gold,.7+Math.random()*.4,3);}}
  if(e.type==='blast'){this.addSprite(e.x,e.y,e.r*.15,e.family==='cryo'?palette.ice:palette.gold,.4);this.ring(e.x,e.y,e.r,e.family==='electric'?palette.mint:palette.gold,.6);}
  if(e.type==='sonar'){this.ring(e.x,e.y,e.r,palette.mint,1.1);this.ring(e.x,e.y,e.r*.7,palette.mint,.8);this.shake=.32;}
  if(e.type==='arc')this.lightning(e);
  if(e.type==='frost'){this.ring(e.x,e.y,e.r,palette.ice,e.active?.9:.35);if(e.active)this.addSprite(e.x,e.y,28,palette.ice,.7);}
  if(e.type==='heal'){this.label(e,'+'+e.value+' HULL','#9de8bd',true);this.ring(e.x,e.y,95,palette.mint,.6);}
  if(e.type==='chest'){this.addSprite(e.x,e.y,15,palette.gold,1.5,2);this.ring(e.x,e.y,150,palette.gold,1.2);}
  if(e.type==='level'||e.type==='artifact'||e.type==='evolution'){if(this.game)this.ring(this.game.p.x,this.game.p.y,180,e.type==='level'?palette.mint:palette.violet,1);}
  if(e.type==='mineralFire'){this.ring(e.x,e.y,e.r,0xff9248,4);this.addSprite(e.x,e.y,16,0xfa7842,4,.3);}
  if(e.type==='bossCharge'){this.ring(e.x,e.y,220,palette.red,.9);this.addSprite(e.x,e.y,12,palette.red,.6);}
  if(e.type==='hit')this.shake=.6;
 }
 syncShip(game){const signature=game.hull+'|'+game.tier+'|'+game.moduleOrder.map(k=>k+':'+(game.modules[k].evolution||'')).join(',');if(signature!==this.shipSignature){const old=this.entities.get('player');if(old)this.release(old);const o=this.createShip(game.hull,game.moduleOrder,game.tier,true);o.children.forEach(m=>{if(m.userData.module&&game.modules[m.userData.module]?.evolution){const halo=new THREE.Mesh(new THREE.TorusGeometry(.8,.035,6,32),new THREE.MeshBasicMaterial({color:0xffcd7e,transparent:true,opacity:.7}));halo.rotation.x=Math.PI/2;halo.position.y=.25;m.add(halo);}});this.entities.set('player',o);this.scene.add(o);this.shipSignature=signature;}const o=this.entities.get('player'),p=game.p;o.position.set(p.x*S,2.1+Math.sin(this.clock*1.5)*.09,p.y*S);o.rotation.y=-p.a;o.rotation.z=Math.sin(this.clock*1.3)*.014;o.scale.setScalar(1+(game.tier-1)*.12);if(p.boosting&&Math.random()<.7)this.addSprite(p.x-Math.cos(p.a)*65,p.y-Math.sin(p.a)*65,2,palette.mint,.6,.5);
  if(p.shield>0||p.hit>0){if(!this.shield){this.shield=new THREE.Mesh(new THREE.SphereGeometry(7,24,16),new THREE.MeshBasicMaterial({color:0x94fce1,wireframe:true,transparent:true,opacity:.08,depthWrite:false}));this.scene.add(this.shield);}this.shield.visible=true;this.shield.position.copy(o.position);this.shield.position.y+=2;}else if(this.shield)this.shield.visible=false;
 }
 syncEnemies(game){const ids=new Set(['player']);for(const e of game.enemies){ids.add(e.id);let o=this.entities.get(e.id);if(!o){if(e.kind==='shoal'){o=new THREE.Mesh(new THREE.CapsuleGeometry(.27,.55,2,5),new THREE.MeshStandardMaterial({color:0xe6b56a,metalness:.3,roughness:.35,emissive:0x402706}));o.geometry.rotateZ(Math.PI/2);}else {const hull=e.kind==='boss'?'dreadnought':'corsair',mods=e.kind==='boss'?['torpedo','flak','mortar','arc']:e.kind==='elite'?['torpedo','flak','mortar']:e.kind==='fort'?['torpedo','flak']:e.kind==='gunner'?['flak']:['torpedo'];o=this.createShip(hull,mods,e.kind==='boss'?3:1,false);}this.scene.add(o);this.entities.set(e.id,o);}const scale=e.kind==='shoal'?1:e.kind==='boss'?2:e.kind==='elite'?1.3:e.r/43;o.scale.setScalar(scale);o.position.set(e.x*S,e.kind==='shoal'?1.6:2+Math.sin(this.clock+e.id)*.08,e.y*S);o.rotation.y=-e.a;o.visible=Math.hypot(e.x-game.p.x,e.y-game.p.y)<1450;}
  for(const [id,o]of this.entities)if(!ids.has(id)){this.release(o);this.entities.delete(id);}
 }
 syncProps(game){const ids=new Set();for(const p of game.props){ids.add(p.id);let o=this.props.get(p.id);if(!o){const model=({habitat:'colony',cache:'chest',wreck:'wreck',repair:'repair',shipyard:'shipyard',chest:'chest'})[p.kind];o=new THREE.Group();const body=this.clone(model);o.add(body);o.userData.body=body;if(p.kind==='chest'||p.kind==='repair'||p.kind==='shipyard'){const color=p.kind==='chest'?palette.gold:p.kind==='repair'?palette.mint:palette.ice;const m=new THREE.SpriteMaterial({map:this.lightTexture,color,transparent:true,opacity:.65,depthWrite:false,blending:THREE.AdditiveBlending});const s=new THREE.Sprite(m);s.position.y=p.kind==='chest'?2.8:5;s.scale.set(3,7,1);o.add(s);o.userData.beacon=s;const ring=new THREE.Mesh(new THREE.RingGeometry(3.9,4.1,48).rotateX(-Math.PI/2),new THREE.MeshBasicMaterial({color,transparent:true,opacity:.3,depthWrite:false,side:THREE.DoubleSide}));ring.position.y=.15;o.add(ring);o.userData.ring=ring;}this.props.set(p.id,o);this.scene.add(o);}const y=seabedHeight(p.x*S,p.y*S,game.stage);o.position.set(p.x*S,y+.1,p.y*S);o.rotation.y=p.a;const scale=p.kind==='habitat'?1+p.tier*.25:p.kind==='chest'?1.35:p.kind==='wreck'?1.1:1;o.scale.setScalar(scale);o.visible=!p.used&&Math.hypot(p.x-game.p.x,p.y-game.p.y)<1450;if(o.userData.beacon)o.userData.beacon.material.opacity=.45+Math.sin(this.clock*2+p.id)*.2;}
  for(const [id,o]of this.props)if(!ids.has(id)){this.release(o);this.props.delete(id);}
 }
 syncProjectiles(game){const ids=new Set();for(const b of [...game.projectiles,...game.mines.map(m=>({...m,key:'mine'}))]){ids.add(b.id);let o=this.bullets.get(b.id);if(!o){const color=b.enemy?palette.red:b.key==='mine'?palette.gold:b.key==='harpoon'?0xddd9b6:b.key==='drone'?palette.mint:palette.gold;const geo=b.key==='mine'?new THREE.IcosahedronGeometry(.45,0):new THREE.CapsuleGeometry(b.enemy?.22:.14,b.key==='harpoon'?1.5:.6,2,5).rotateZ(-Math.PI/2);o=new THREE.Mesh(geo,new THREE.MeshStandardMaterial({color,emissive:color,emissiveIntensity:1.6,metalness:.5,roughness:.3}));this.bullets.set(b.id,o);this.scene.add(o);}o.position.set(b.x*S,3.6+(b.height||0)*S,b.y*S);o.rotation.y=-(b.a||0);if(b.key==='mine'){o.position.y=2;o.rotation.y=this.clock*.3;}if(b.key==='torpedo'&&Math.random()<.25)this.addSprite(b.x,b.y,.65,palette.mint,.3);}
  for(const [id,o]of this.bullets)if(!ids.has(id)){this.scene.remove(o);o.geometry.dispose();o.material.dispose();this.bullets.delete(id);}
 }
 syncGold(game){this.gold.count=Math.min(750,game.loot.length);for(let i=0;i<this.gold.count;i++){const l=game.loot[i];this.dummy.position.set(l.x*S,2.2+Math.sin(this.clock*3+l.id)*.3,l.y*S);this.dummy.rotation.set(this.clock+l.id,this.clock*2,0);this.dummy.scale.setScalar(l.value>5?1.5:1);this.dummy.updateMatrix();this.gold.setMatrixAt(i,this.dummy.matrix);}this.gold.instanceMatrix.needsUpdate=true;}
 project(x,y,height=3){const v=new THREE.Vector3(x*S,height,y*S).project(this.camera);return {x:(v.x*.5+.5)*innerWidth,y:(-.5*v.y+.5)*innerHeight};}
 update(dt,game){this.clock+=dt;if(this.loading){this.renderer.render(this.scene,this.camera);return;}this.shake*=Math.exp(-dt*9);const t=this.clock;
  if(game){if(this.stage!==game.stage)this.setStage(game.stage);this.worldView.setRegion(game.stage,game.worldSeed||1927,game.world?.landmarks||[]);this.focus.lerp(new THREE.Vector3(game.p.x*S,0,game.p.y*S),1-Math.exp(-dt*5));this.syncShip(game);this.syncEnemies(game);this.syncProps(game);this.syncProjectiles(game);this.syncGold(game);if(this.menuModel)this.menuModel.visible=false;}
  else {this.worldView.setRegion(0,1927,[],true);if(this.menuModel){this.menuModel.visible=true;this.menuModel.rotation.y=.48+Math.sin(t*.13)*.12;this.menuModel.position.y=6+Math.sin(t*.8)*.13;}this.focus.lerp(new THREE.Vector3(0,0,0),1-Math.exp(-dt*4));if(this.stage!==0)this.setStage(0);}
  this.repositionDeco(this.focus.x,this.focus.z);this.worldView.update(dt,this.focus,this.camera,game);this.plankton.rotation.y=Math.sin(t*.05)*.025;
  for(let i=0;i<100;i++){const flock=Math.floor(i/10),j=i%10,x=this.focus.x+(hash(flock+700)-.5)*150+Math.sin(t*.06+flock)*20,z=this.focus.z+(hash(flock+800)-.5)*110;this.dummy.position.set(x+j*.9,4+hash(flock)*10+Math.sin(t*.9+i)*.2,z+Math.sin(j*2.4)*1.8);this.dummy.rotation.set(0,Math.sin(t*.06+flock)*.15,0);this.dummy.scale.setScalar(.5+hash(flock)*.5);this.dummy.updateMatrix();this.fish.setMatrixAt(i,this.dummy.matrix);}this.fish.instanceMatrix.needsUpdate=true;
  for(let i=this.fx.length-1;i>=0;i--){const f=this.fx[i];f.life-=dt;if(f.life<=0){this.release(f.obj);this.fx.splice(i,1);continue;}const a=1-f.life/f.max;f.obj.material.opacity=(1-a)*(f.type==='sprite'?.8:.75);if(f.type==='ring')f.obj.scale.setScalar(Math.max(.01,f.size*a));if(f.type==='sprite'){f.obj.scale.setScalar(f.size*(1+a*.7));f.obj.position.y+=(f.vy||0)*dt;}}
  const offset=game?new THREE.Vector3(0,90,76):new THREE.Vector3(0,75,74);this.camera.position.copy(this.focus).add(offset);this.camera.position.x+=(Math.random()-.5)*this.shake;this.camera.position.z+=(Math.random()-.5)*this.shake;this.camera.lookAt(this.focus);this.sun.position.copy(this.focus).add(new THREE.Vector3(-40,85,15));this.sun.target.position.copy(this.focus);this.sun.target.updateMatrixWorld();
  for(let i=this.damageTexts.length-1;i>=0;i--){const d=this.damageTexts[i];d.age+=dt;if(d.age>d.life){d.el.remove();this.damageTexts.splice(i,1);continue;}const p=this.project(d.x/S,d.z/S,7+d.age*3);d.el.style.transform=`translate(${p.x}px,${p.y}px)`;d.el.style.opacity=String(Math.min(1,(d.life-d.age)*3));}
  this.post.render(this.scene,this.camera);
 }
 get stats(){return {bloom:this.post?.enabled,antialiasSamples:this.post?.target.samples||0,calls:this.post?.stats?.calls??this.renderer.info.render.calls,triangles:this.post?.stats?.triangles??this.renderer.info.render.triangles,world:this.worldView?.stats,geometries:this.renderer.info.memory.geometries,textures:this.renderer.info.memory.textures,assets:Object.keys(this.assets).length};}
}
